### ISSUE TITLE
SpringBoard & Phone preferences crash

### ISSUE THREAD

**Issue by simoselis** [MTACS/Lynx#1]
When I try to check the PreferenceBundle, it crashes the Settings.app on "SpringBoard" and "Phone".
Log from Cr4shed and Tweak List attached.
[Crash Log.txt](https://github.com/MTACS/Lynx/files/4066081/Crash.Log.txt)
[Tweak List.txt](https://github.com/MTACS/Lynx/files/4066082/Tweak.List.txt)

**Comment by MTACS** [comment]
What iOS version are you using?

**Comment by simoselis** [comment]
iOS 13.3/iPhone 7 (GSM), you can see it in the crash log too

**Comment by MTACS** [comment]
Seems I forgot to add cephei and libcolorpicker as dependencies, the next update should fix this

**Comment by simoselis** [comment]
Can confirm that installing those dependencies (I had to uninstall libcolorpicker-nepeta and substitute it with libcolorpicker) resolved the issue.
