### ISSUE TITLE
Some settings not applying (Little11 incompatibility?)

### ISSUE THREAD

**Issue by zibo29** [MTACS/Lynx#10]
**Describe the bug**
Settings like “hide folder icon background”  not applied 
**To Reproduce**
Install little11 

**Expected behavior**

**Screenshots**

**iDevice Information (please complete the following information):**
 - Device: [iPhone 7 Plus]
 - OS: [iOS 13.2.2]
 - Package Manager used to install Lynx [Cydia]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.0.3]

**Additional context**

**Comment by MTACS** [comment]
It was something broken in the way that I hide it, I'll have an update out in a few minutes
