### ISSUE TITLE
Settings Cells not using modern layout when selected

### ISSUE THREAD

**Issue by medichylton** [MTACS/Lynx#104]
Settings Pane not using modern layout when selected.

Settings>Lynx>System Wide>Modern Layout✅ All apps selected, Hide Cell Icons✅

Also self-troubleshooted: Unselected all apps but settings, all apps, unselected hide cell icons.

![FA5D671E-B79A-41F5-8E3D-10C5E8E1C44B](https://user-images.githubusercontent.com/14093079/76712148-32ded200-66ec-11ea-83f8-845dc01d4287.png)
![00179C26-22F9-4FE5-85FD-FC3F3239E619](https://user-images.githubusercontent.com/1409 3079/76712149-36725900-66ec-11ea-910b-5a347a2f6473.png)

iPhone XR, 13.3
Zebra used to install Lynx Version 1.1.8

Thank you

**Comment by MTACS** [comment]
Fixed in 1.1.8-1, update will be pushed soon
