### ISSUE TITLE
Missing Reddit icon, and incorrect SoundCloud icon

### ISSUE THREAD

**Issue by noahmaranesi** [MTACS/Lynx#105]
**Missing Reddit icon**

1. Lynx → Third Party Apps → **Reddit**

---

**Incorrect SoundCloud icon**

1. Lynx → Third Party Apps → **SoundCloud**

---

I recommend going to **[icons8.com](https://icons8.com)**. They have both logos downloadable for free in various different styles.

**Comment by MTACS** [comment]
I have a designer who makes all the icons, and the SoundCloud icon is a custom one, not the same as the official app icon. The missing Reddit icon will be fixed in the next update
