### ISSUE TITLE
Pixel bug when opening/closing app

### ISSUE THREAD

**Issue by redzrex** [MTACS/Lynx#109]
**Describe the bug**
When opening or closing an app, a slight pixel or image of the app colour will show up for an instance

**To Reproduce**
Steps to reproduce the behavior: Opening or closing app

**Expected behavior**
App should  not show that pixel/image when opening or closing the app

**Screenshots**
https://imgur.com/gallery/EbWst8E

**iDevice Information (please complete the following information):**
 - Device: [iPhone XS MAX]
 - OS: [iOS 13.3]
 - Package Manager used to install Lynx: [Zebra]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.1.8]
 - Jailbreak Used: [unc0ver]

**Additional context**
This problem does not occurs when Lynx is uninstalled. I already tried finding any settings that would cause this but couldn't find it.

**Comment by MTACS** [comment]
Fixed in 1.1.8-4
