### ISSUE TITLE
Lockscreen Page Dots. iPhone 8 Plus

### ISSUE THREAD

**Issue by junkFOx-x** [MTACS/Lynx#110]
**Describe the bug**
Hiding lockscreen page dots doesn’t work on my device. 

**To Reproduce**
Go to lynx / lockscreen
Enable “Hide Page Dots”

**Expected behavior**
The page dots to hide. 

**Screenshots**
N/A

**iDevice Information (please complete the following information):**
 - Device: iPhone 8 Plus. 
 - OS: [iOS 13.3]
 - Package Manager used to install Lynx: Cydia
 - Lynx Version (Can be found at the bottom of Settings pane): 1.1.8
 - Jailbreak Used: unc0ver

**Comment by MTACS** [comment]
Fixed in a recent update

**Comment by junkFOx-x** [comment]
This is not fix in version 1.1.8-6. iPhone 8 Plus 13.3
