### ISSUE TITLE
Change number of dock icons not working

### ISSUE THREAD

**Issue by RealWitchyShit** [MTACS/Lynx#118]
**Describe the bug**
No changes occur when I increase the number of dock icons from 4

**To Reproduce**
Set number above 4, respring, dock count sits at 4

**Expected behavior**
Expected the number of icons to change to the number I changed it to

**iDevice Information (please complete the following information):**
 - Device: 8 plus
 - OS: iOS 13.3.1
 - Package Manager used to install Lynx: Zebra
 - Lynx Version: 1.1.8
 - Jailbreak Used: Checkra1n

**Additional context**
I removed all other tweaks pertaining to the dock/homescreen to make sure there were no conflicts and still couldn't get it to work. Hide dock background DOES work however, as does changing the column count in the homescreen.

**Comment by MTACS** [comment]
Would you be able to post a video of it? Just tried it on my 8+, 7 and X and it seemed to be working

**Comment by RealWitchyShit** [comment]
Never mind, I'm an idiot. Never actually tried ADDING more icons to the dock. It works perfectly.

**Comment by MTACS** [comment]
Was gonna ask if you tried that 😂Glad it's fixed
