### ISSUE TITLE
There is no zoom button/slider when using iPad style camera.

### ISSUE THREAD

**Issue by DamnRobotAliens** [MTACS/Lynx#122]
**Describe the bug**
No zoom button when using iPad style camera.

**To Reproduce**

**Expected behavior**

**Screenshots**

**iDevice Information (please complete the following information):**
 - Device: [iPhone X]
 - OS: [iOS 13.3]
 - Package Manager used to install Lynx: [Zebra]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.1.8]
 - Jailbreak Used: [unc0ver]

**Additional context**

**Comment by MTACS** [comment]
This is due to the way in which I forced it to use the style, there isn’t a way I can access the zoom slider to try and change its position, pinch to zoom does still with though
