### ISSUE TITLE
The "Hide Page Dots" option also hides page dots in other apps (Delta emu).

### ISSUE THREAD

**Issue by OngoGablogian** [MTACS/Lynx#125]
**Describe the bug**
Enabling the "Hide Page Dots" option also hides the page dots in other apps. Currently I've only seen it happen in "[Delta](https://github.com/rileytestut/Delta)" by Riley Testut.

**To Reproduce**
Enable "Hide Page Dots" with Delta installed.

**Expected behavior**
Page dots should appear at the bottom of the screen when you have ROMs from at least two systems in your library (one page per emulated console). 

**Screenshots**
[screenshot](https://i.imgur.com/Ueddn0E.png)

**iDevice Information (please complete the following information):**
 - Device: [iPhone X]
 - OS: [iOS 13.3]
 - Package Manager used to install Lynx: [Zebra]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.1.8-5]
 - Jailbreak Used: [Checkra1n]

**Comment by MTACS** [comment]
I’ll add a check to make sure it is only on SpringBoard and will be included in the next update

**Comment by OngoGablogian** [comment]
Great, thank you :)

**Comment by MTACS** [comment]
Fixed in 1.1.8-7
