### ISSUE TITLE
LYNX BUG

### ISSUE THREAD

**Issue by z306334796** [MTACS/Lynx#126]
**Describe the bug**
After installing the latest version of LYNX, a FLEX adjustment for the settings application no longer takes effect, but in previous versions, this adjustment was available. And only if I completely disable LYNX can I solve this problem.
**To Reproduce**

**Expected behavior**

**Screenshots**

**iDevice Information (please complete the following information):**
 - Device: [iPhone Xs Max]
 - OS: [iOS 13.3]
 - Package Manager used to install Lynx: [Zebra]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.1.8-6]
 - Jailbreak Used: [unc0ver]

**Additional context**

**Comment by z306334796** [comment]
![微信图片_20200319195157](https://user-images.githubusercontent.com/21018730/77064868-3ee3d000-6a1b-11ea-80f5-91fd8bc44f43.png)

**Comment by MTACS** [comment]
Fixed in 1.1.8-7 but reworking logic of Lynx's modern table cell design
