### ISSUE TITLE
Option to hide home bar only on lockscreen

### ISSUE THREAD

**Issue by allendude51** [MTACS/Lynx#127]
Can you add an option to only hide the home bar on the lockscreen? I don't like it being hidden everywhere.

**Comment by nguyenthienhoan** [comment]
here is only hide homebar in lock screen
%hook CSTeachableMomentsContainerView
-(void)setHomeAffordanceContainerView:(UIView *)arg1{
    return;
}
%end

**Comment by MTACS** [comment]
Added in 1.1.8-7

**Comment by allendude51** [comment]
Thanks! Also I noticed a bug on 4.7 inch devices. The option to hide the page dots on the lockscreen isn't working.

**Comment by MTACS** [comment]
Is it just that device size? I have all devices to test on so I’ll do a little digging myself

**Comment by allendude51** [comment]
Well I have 2 6s and I have the option enabled on both but the page dots are still there. Don't know about other sizes though.

**Comment by MTACS** [comment]
I’ll change the way I hide them, I don’t normally use those devices so I completely overlooked it, thank you for pointing it out

**Comment by allendude51** [comment]
Also just a small feature suggestion. I think the option to hide the like number on Instagram should be off by default and turning the toggle to ON should hide them.

**Comment by allendude51** [comment]
And no problem and thanks for the quick responses!
