### ISSUE TITLE
Dock Hide partially works

### ISSUE THREAD

**Issue by jkauf55** [MTACS/Lynx#131]
**Describe the bug**
When you enable Hide Completely under Dock section it hides the dock but the icons that are in the bottom area are unresponsive when touched

**To Reproduce**
Open Lynx
Go into System Wide
Under Dock enable Hide Completely 
Back out and hit Apply
After respring and using (in my case Boxy) I move last row of icons to bottom of screen where dock icons originally were. 
Press on any icon on bottom row and it does nothing

**Expected behavior**
Unresponsive icons when pressed

**Screenshots**
![5B8267C8-DEF1-46FD-AC4A-5E99C27D0844](https://user-images.githubusercontent.com/24393422/77216424-31484c00-6ae8-11ea-8434-d05922f2cebb.jpeg)
Circled row are the nonresponsive icon when Hide Completely is turned ON AFTER moving icons down the screen

**iDevice Information (please complete the following information):**
 - Device: [iPhone XS Max]
 - OS: [iOS 13.3]
 - Package Manager used to install Lynx: [Cydia]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.1.8]
 - Jailbreak Used: [unc0ver]

**Additional context**

**Comment by MTACS** [comment]
I rewrote it to have a proper fix and will be included in the next update
