### ISSUE TITLE
Bluetooth no working:/

### ISSUE THREAD

**Issue by ANDREW209** [MTACS/Lynx#132]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**iDevice Information (please complete the following information):**
 - Device: [iPhone X]
 - OS: [iOS 13.2.2]
 - Package Manager used to install Lynx: [Zebra, Cydia, Installer]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.0.3]
 - Jailbreak Used: [Checkra1n, unc0ver]

**Additional context**

**Comment by MTACS** [comment]
Could you provide some more detail? Also try disabling all other tweaks except Lynx and see if the issue persists. I test on the exact same device and iOS version and it is working perfectly for me
