### ISSUE TITLE
Status Bar Location Icon

### ISSUE THREAD

**Issue by Misl3d** [MTACS/Lynx#133]
Hiding the location arrow in status bar 

![145CE53E-5BCA-4FE1-B3A3-253539A2A06F](https://user-images.githubusercontent.com/55099930/77241771-72fef280-6bcd-11ea-9f70-ec21cbcfb8e5.jpeg)

**Comment by nguyenthienhoan** [comment]
try go to Settings / Privacy / Location Services / System Services /  disable Status Bar Icon

**Comment by Misl3d** [comment]
> try go to Settings / Privacy / Location Services / System Services / disable Status Bar Icon

This will only disable it for system services if apps use location such as the tile app the icon is still there.. 

I have "disable status bar icon" on
