### ISSUE TITLE
Bug with spotify, break spotilife tweak and go the free version.

### ISSUE THREAD

**Issue by kevdriel** [MTACS/Lynx#136]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**iDevice Information (please complete the following information):**
 - Device: [iPhone X]
 - OS: [iOS 13.2.2]
 - Package Manager used to install Lynx: [Zebra, Cydia, Installer]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.0.3]
 - Jailbreak Used: [Checkra1n, unc0ver]

**Additional context**

**Comment by MTACS** [comment]
It’s an issue with Spotilife, Lynx is explicitly disabled in Spotify

**Comment by MTACS** [comment]
Not sure what you mean by the fee version...it’s an issue with Spotilife somehow as Lynx is not injected info Spotify at all

**Comment by emlapzo9x** [comment]
Use Choicy disable Lynx on spotify and it will work  flawlessly

**Comment by emlapzo9x** [comment]
> Not sure what you mean by the free version...it’s an issue with Spotilife somehow as Lynx is not injected info Spotify at all

I know, but somehow it breaks spotify. Use my method and it worked again
