### ISSUE TITLE
Hide “Notification Center” text not working (Little11 incompatibility?)

### ISSUE THREAD

**Issue by zibo29** [MTACS/Lynx#14]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**iDevice Information (please complete the following information):**
 - Device: [iPhone 7 Plus]
 - OS: [iOS 13.2.2]
 - Package Manager used to install Lynx [Cydia]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.0.3]

**Additional context**

**Comment by MTACS** [comment]
Try setting it to an empty string, if that doesn't work I'll add a separate toggle

**Comment by zibo29** [comment]
> Try setting it to an empty string, if that doesn't work I'll add a separate toggle

That worked! Thanks!
