### ISSUE TITLE
Internal features 

### ISSUE THREAD

**Issue by therealhoodboy** [MTACS/Lynx#140]
**Is your feature request related to a problem? Please describe.**
My feature is not related to a problem. 

**Describe the solution you'd like**
I would like to have some apple internal options, like in photos app, to enable the internal settings. Or enable the prototype settings on springboard. 

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by MTACS** [comment]
I might be able to with Photos, but the methods for prototype settings in iOS 13 were removed

**Comment by therealhoodboy** [comment]
Okay. I assumed that they must have changed something under the hood, cause every internal tweak became broken. Thanks.
