### ISSUE TITLE
Reddit coins show in Lynx with disabled option

### ISSUE THREAD

**Issue by devhost97** [MTACS/Lynx#144]
**Describe the bug**
Reddit coins is still showing after disable in Lynx
![image](https://user-images.githubusercontent.com/25454629/77562463-56f69c00-6ec0-11ea-97ca-529cf9da11a5.png)

**To Reproduce**

Update to newest version.

**iDevice Information (please complete the following information):**
* Device: [iPhone 8]
* OS: [iOS 13.4]
* Package Manager used to install Lynx [Zebra]
* Lynx Version: [1.1.9-3]

**Comment by MTACS** [comment]
Reddit changed something in the latest version, I'm working on a fix for the next update
