### ISSUE TITLE
Spotlight Issue

### ISSUE THREAD

**Issue by ziegwald** [MTACS/Lynx#145]
**Describe the bug**
I have disabled spotlight in a tweak called zenith. However, after I updated lynx to version 1.1.9-5 and 1.1.9-6, the spotlight is activated whenever I swipe down in homescreen.

**To Reproduce**
Spotlight is activated whenever I swipe down in homescreen after updating lynx.

**Expected behavior**
Spotlight should have been disabled.

**iDevice Information (please complete the following information):**
 - Device: [iPhone XS MAX]
 - OS: [iOS 13.3]
 - Package Manager used to install Lynx: [Cydiq]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.1.9-5, 1.1.9-6]
 - Jailbreak Used: [Unc0ver]

**Additional context**
I tried to downgrade lynx with cydia, but it made lynx not working at all.

**Comment by MTACS** [comment]
It’s why it’s in the experimental options, I’m working with the dev of Zenith to make sure both tweaks are compatible

**Comment by ziegwald** [comment]
Sorry, I managed to disable it under experimental tab just now. I didn't have to do this with previous versions though, so i wonder why this happened.

**Comment by MTACS** [comment]
It’s because it’s conflicting with the tweak Zenith and until I can find a definite fix by working with it’s developer it’ll remain here until I can get it working perfectly
