### ISSUE TITLE
Installing Lynx causes issues in share sheet

### ISSUE THREAD

**Issue by SuperTachyon** [MTACS/Lynx#149]
**Describe the bug**
When Lynx is installed (not need to enable), some share sheet extensions can’t get passed the correct items. For example, DEVONthink To Go only can’t get any file but only its file path.

**To Reproduce**
1. Install Lynx and DEVONthink To Go
2. Share a file via Share Sheet using DEVONthink’s extension 
3. DEVONthink only gets the path of the file instead of the actual file

**Expected behavior**
DEVONthink should get the actual file shared

**iDevice Information (please complete the following information):**
 - Device: [iPad Pro 10.5]
 - OS: [iOS 13.4]
 - Package Manager used to install Lynx: [Zebra]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.1.9-6]
 - Jailbreak Used: [Checkra1n]

**Additional context**
It’s probably a niche issue. I’m not sure what’s changed by installing Lynx that could cause issues in Share Sheet.

**Comment by MTACS** [comment]
Would I be able to get the name of the apps executable or bundleID so I can blacklist?

**Comment by SuperTachyon** [comment]
"bundleId":"com.devon-technologies.thinktogo"

**Comment by SuperTachyon** [comment]
I’m not sure if the host apps (the apps I’m sharing from, including Files, Safari, GoodReader and etc.) or devonthink (the app I’m sharing to) should be blacklisted though.

**Comment by MTACS** [comment]
I’d say Devonthink as share sheet actions are part of the app, I’ll add its bundle ID and process name if I can find it

**Comment by SuperTachyon** [comment]
Thank you!

**Comment by SuperTachyon** [comment]
Just updated to 1.2.0-3. Unfortunately this issue is still present.
