### ISSUE TITLE
Home Bar not hiding in reachability (little11 incompatibility?)

### ISSUE THREAD

**Issue by zibo29** [MTACS/Lynx#16]
**Describe the bug**
As described, it could be simpler to add an option to hide the homebar everywhere?

**To Reproduce**

**Expected behavior**

**Screenshots**

**iDevice Information (please complete the following information):**
 - Device: [iPhone X]
 - OS: [iOS 13.2.2]
 - Package Manager used to install Lynx [Zebra, Cydia, Installer]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.0.3]

**Additional context**

**Comment by MTACS** [comment]
The report says your using version 1.0.3, if that's the case then please update to the latest version. I just tested it on my iPhone X 13.2.2 and it was working fine

**Comment by zibo29** [comment]
> The report says your using version 1.0.3, if that's the case then please update to the latest version. I just tested it on my iPhone X 13.2.2 and it was working fine

Using 1.0.7 - my mistake sending the bug without changing the version

**Comment by MTACS** [comment]
Does the homebar reappear when swiping down to open reachability?

**Comment by zibo29** [comment]
> Does the homebar reappear when swiping down to open reachability?

Exactly! No homebar in home screen but it reappears when using reachability (iPhone 7 Plus with Little11)

![A63260BD-3536-4CFF-99F9-005352179AF2](https://user-images.githubusercontent.com/6270589/72686699-c1254600-3af7-11ea-8ac4-ae192e040e9d.png)

**Comment by MTACS** [comment]
Oh it’s with a different tweak, I’ll install on my 7 and test it

**Comment by zibo29** [comment]
It also shows up when 3D touching on a notification. So a “disable homebar everywhere” option would be ideal.
(I’m open to beta testing if needed, thanks)

![6085E45B-3457-4F07-8C1E-EEF421DD28FB](https://user-images.githubusercontent.com/6270589/72687098-23cc1100-3afb-11ea-8375-934fba18b63c.png)

**Comment by MTACS** [comment]
Turns out its a bug with Little11, I tried forcing it to hide when the tweak was installed but it made the control center unusable, not much I can do as it seems to be overriding any of my hooks

**Comment by zibo29** [comment]
Don’t know, Artemis was able to hide it so there should be some way... also HidebarX does the trick, if they’re open source you could take a look at those

**Comment by MTACS** [comment]
I’ll add a hide home bar everywhere option, I gotta look into it more, it
seems it may use a completely different method of showing it

**Comment by zibo29** [comment]
> I’ll add a hide home bar everywhere option, I gotta look into it more, it seems it may use a completely different method of showing it
> […](#)

It this could help (
