### ISSUE TITLE
disable haptic touch, this from Sunflower repo Chariz

### ISSUE THREAD

**Issue by nguyenthienhoan** [MTACS/Lynx#168]
%hook _UITouchDurationObservingGestureRecognizer
-(double)minimumDurationRequired {
return 1000;
}
%end

**Comment by MTACS** [comment]
I’ve tested this extensively, but it’s more than just this, I have it on my experimental branch and hopefully will have it ready soon

**Comment by samwllson9478** [comment]
Does this mean disable it completely throughout the whole device?

**Comment by nguyenthienhoan** [comment]
> Does this mean disable it completely throughout the whole device?

yes, about 6s to X it work in ios 13 . ios 12 i dont knos
