### ISSUE TITLE
Disable Control Center Gap (FUGap alternative)

### ISSUE THREAD

**Issue by zibo29** [MTACS/Lynx#17]
**Is your feature request related to a problem? Please describe.**
With Little11 installed, you get a huge gap between the status bar and the toggles in the CC

**Describe the solution you'd like**
Hide the gap, just like FUGap does

**Describe alternatives you've considered**
Since your tweak is replacing a lot of tweaks, this one would be another one to go

**Comment by MTACS** [comment]
I'll look into it
