### ISSUE TITLE
Lynx Problem with my folders

### ISSUE THREAD

**Issue by henriquebdf** [MTACS/Lynx#174]
Hi 

After upgrade to the latest version,some folders on my device are rounded
My info: iPhone X  iOS 13.3  Unc0ver 4.3.1

Thank you !
![9923C013-8E03-466B-AD51-F3064736E220](https://user-images.githubusercontent.com/63331765/78743680-b11e4500-7935-11ea-8920-ea3579fb3c82.jpeg)

**Comment by MTACS** [comment]
Just pushed 1.2.2 to fix this a few seconds ago, let me know if you face any more issues with it

**Comment by henriquebdf** [comment]
See this image ! ![image](https://user-images.githubusercontent.com/63331765/78745630-20e2fe80-793b-11ea-9548-3728f388b537.jpeg)


> Just pushed 1.2.2 to fix this a few seconds ago, let me know if you face any more issues with it

**Comment by henriquebdf** [comment]
Now is Okay! 

Thank you !

> See this image ! ![image](https://user-images.githubusercontent.com/63331765/78745630-20e2fe80-793b-11ea-9548-3728f388b537.jpeg)
> 
> 
> > Just pushed 1.2.2 to fix this a few seconds ago, let me know if you face any more issues with it
