### ISSUE TITLE
Lock screen icon

### ISSUE THREAD

**Issue by cilin1105** [MTACS/Lynx#175]
Option to hide lock icon on screen lock
![45193A87-0EB6-4439-ACE1-64B41BB95826](https://user-images.githubusercontent.com/35177675/78839634-df983080-79c6-11ea-9ef3-8496018d5a03.jpeg)

THIS IS A REQUEST NOT AN ISSUE...

**Comment by MTACS** [comment]
Lynx > Lockscreen > Passcode screen > Hide FaceID padlock

**Comment by cilin1105** [comment]
> Lynx > Lockscreen > Passcode screen > Hide FaceID padlock

Just work in passcode screen(
![819D53D3-02C4-4BE1-B9F1-F9D027605CF1](https://user-images.githubusercontent.com/35177675/78890880-718a5280-7a34-11ea-9ddf-459b44d1ebc9.jpeg)

![5260BC0D-98C8-42DE-B062-1F96F342F2F6](https://user-images.githubusercontent.com/35177675/78891060-c1691980-7a34-11ea-8a2a-8d1d5f57ade9.png)


Not work in lockscreen 
![Uploading 48D4FCF8-9208-4CBD-89D4-AD2C1CA02F0F.jpeg…]()
