### ISSUE TITLE
Lockscreen icon

### ISSUE THREAD

**Issue by cilin1105** [MTACS/Lynx#176]
Option to hide lock icon on screen lock
![45193A87-0EB6-4439-ACE1-64B41BB95826](https://user-images.githubusercontent.com/35177675/78839634-df983080-79c6-11ea-9ef3-8496018d5a03.jpeg)

**Comment by cilin1105** [comment]
> Lynx > Lockscreen > Passcode screen > Hide FaceID padlock

Just work in passcode screen(
![819D53D3-02C4-4BE1-B9F1-F9D027605CF1](https://user-images.githubusercontent.com/35177675/78890880-718a5280-7a34-11ea-9ddf-459b44d1ebc9.jpeg)

![5260BC0D-98C8-42DE-B062-1F96F342F2F6](https://user-images.githubusercontent.com/35177675/78891060-c1691980-7a34-11ea-8a2a-8d1d5f57ade9.png)


Not work in lockscreen like my first pic on first comment. Lockscreen and passcode screen are 2 different screen

**Comment by MTACS** [comment]
What other lockscreen tweaks are you using? It's hiding fine for me on both screens without any other tweaks installed

**Comment by cilin1105** [comment]
My apologies works like a charm, but have conflict with xen html. May be compatibility in feture versions.

**Comment by MTACS** [comment]
At some point I will reach out to it’s developer to see what I can do.
