### ISSUE TITLE
Photos debug info not showing up 

### ISSUE THREAD

**Issue by therealhoodboy** [MTACS/Lynx#177]
**Describe the bug**
The experimental feature "Show Debug Info" for the photos app does not work unfortunately.  

**To Reproduce**
1. Enable debug menu inside the tweak settings. 
2. Open photos. 

**Expected behavior**
I expected a little gear-icon anywhere to open the menu, additionally maybe some more information about a photo. 

**Screenshots**
No screenshots are applicable.

**iDevice Information (please complete the following information):**
 - Device: [iPhone XR]
 - OS: [iOS 13.3]
 - Package Manager used to install Lynx: [Cydia]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.2.3]
 - Jailbreak Used: [unc0ver]

**Additional context**
-

**Comment by MTACS** [comment]
It’s only for editing a photo, not sure what other tweaks do but it’s all I could find related to it in the code
