### ISSUE TITLE
Circle folder icons

### ISSUE THREAD

**Issue by berkozarslan** [MTACS/Lynx#178]
**Describe the bug**
Once i used use_circle_icons(for notifications**) on experimental settings and nothing changed. After second try i recognized my folder icons randomly changing to circle and square irregularly and i couldnt revert back to stock. 

**Expected behavior**
Fix the bug that change folder icons.

**Screenshots**
https://www.youtube.com/watch?v=Hamr6XinDw4

**iDevice Information (please complete the following information):**
 - Device: [iPhone 7]
 - OS: [iOS 13.3]
 - Package Manager used to install Lynx: [Cydia]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.2.1]
 - Jailbreak Used: [unc0ver]

**Comment by MTACS** [comment]
This was fixed in newer version, please update to the latest
