### ISSUE TITLE
Hide “Time Limit” label and greyed-out icon

### ISSUE THREAD

**Issue by zibo29** [MTACS/Lynx#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MTACS** [comment]
Would you mind adding requests and stuff into one issue? It’ll make it much easier to track

**Comment by zibo29** [comment]
> Would you mind adding requests and stuff into one issue? It’ll make it much easier to track

Ops thanks, from now on I’ll make a one post only!

**Comment by zibo29** [comment]
Added in 1.0.8
