### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by javferncast** [MTACS/Lynx#181]
**Describe the bug**
The app crashes when I click the “ messages, phone and settings section of the tweak “ an that makes the settings app crash as well making all tweaks disappear until I restoring the device. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**iDevice Information (please complete the following information):**
 - Device: [ iPhone XI pro max iOS 13.3.1 i used zebra to install the tweak. 
 - Lynx Version (Can be found at the bottom of Settings pane): [1.2.4]
 - Jailbreak Used: [unc0ver]

**Additional context**

**Comment by MTACS** [comment]
Do you have a colorpicker installed?
