### ISSUE TITLE
I cannot turn off coin in reddit and its making post icon not show so i cant respond or make a new subject

### ISSUE THREAD

**Issue by rbasrawi** [MTACS/Lynx#184]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**iDevice Information (please complete the following information):**
 - Device: [iPhone X]
 - OS: [iOS 13.2.2]
 - Package Manager used to install Lynx: [Zebra, Cydia, Installer]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.0.3]
 - Jailbreak Used: [Checkra1n, unc0ver]

**Additional context**

**Comment by MTACS** [comment]
Update to the latest version
