### ISSUE TITLE
“Hide Folder icone background” not working for all folders

### ISSUE THREAD

**Issue by zibo29** [MTACS/Lynx#19]
**Describe the bug**
As the title, effect not applies to all folders

**To Reproduce**
Sometime opening and closing the folder applies the effect

**Screenshots**
![4CB45954-2FDE-4A25-B796-A145F8FDE352](https://user-images.githubusercontent.com/6270589/72687409-ce453380-3afd-11ea-9274-02ff283ba4c6.png)

**iDevice Information (please complete the following information):**
 - Device: [iPhone 7 Plus]
 - OS: [iOS 13.2.2]
 - Package Manager used to install Lynx [Cydia]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.0.8]

**Additional context**

**Comment by MTACS** [comment]
Fixed
