### ISSUE TITLE
Show percentage sliders in Control Center

### ISSUE THREAD

**Issue by nguyenthienhoan** [MTACS/Lynx#192]
SugarCane is public project

https://github.com/baptistecdr/SugarCane

**Comment by MTACS** [comment]
I can’t add any open source tweaks to the project and claim them for a price unless I have direct permission from the author

**Comment by nguyenthienhoan** [comment]
i 

> I can’t add any open source tweaks to the project and claim them for a price unless I have direct permission from the author
> […](#)
> On Apr 14, 2020, 2:29 AM -0400, iTer99 ***@***.***>, wrote: SugarCane is public project https://github.com/baptistecdr/SugarCane — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

did you contact to him? User buy Lynx not mean them want buy Lynx, i think Lynx is perfect project all in one.

**Comment by MTACS** [comment]
I'm working on adding it myself, but don't have an eta as I'm writing it from scratch
