### ISSUE TITLE
kill all apps

### ISSUE THREAD

**Issue by ratpackbn** [MTACS/Lynx#196]
kill all apps in the switcher.. or make the tweak compatible with the QuitAll tweak. thanx!

**Comment by MTACS** [comment]
Does swipe down not work?

**Comment by ratpackbn** [comment]
ohh.. maybe u should change the label to “Swipe down to kill all” instead if just “swipe down to kill” 😁

i didn’t know but thanx!

Sent from my iPhone

On 17 Apr 2020, at 11:44 AM, MTAC <notifications@github.com> wrote:

﻿

Does swipe down not work?
