### ISSUE TITLE
Reddit posting bug still not fixed after update

### ISSUE THREAD

**Issue by elishakoch** [MTACS/Lynx#201]
**Describe the bug**
In the change log it said you fixed the reddit posting bug, however, I still could not post after the update. I have reddit version 2020.13.1

**To Reproduce**
Steps to reproduce the behavior: turn on “hide coin button”.

**Expected behavior**
Be able to post with “hide coin button” on.

**Screenshots**
With “hide coin button” on:
https://i.imgur.com/pC99cyQ.png
With “hide coin button” off:
https://i.imgur.com/3lPJ8YM.png

**iDevice Information (please complete the following information):**
 - Device: [iPhone Xr]
 - OS: [iOS 13.3]
 - Package Manager used to install Lynx: [Zebra]
 - Lynx Version: [1.2.6]
 - Jailbreak Used: [unc0ver]

**Additional context**
I’ll survive without it just wanted to let you know.

**Comment by MTACS** [comment]
Try resetting settings

**Comment by elishakoch** [comment]
Then it just doesn’t remove the coin button 
https://i.imgur.com/RbahiXY.png

**Comment by MTACS** [comment]
Wait for 1.2.6-2 to be live on Twickd
