### ISSUE TITLE
Apps are loading *very* slow after updates.  For example, messages app takes at least 5-6 seconds to load upon launching app.  Uninstalled Lynx and everything works fine.  iPhone XR (13.3) Uncover

### ISSUE THREAD

**Issue by medichylton** [MTACS/Lynx#204]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**iDevice Information (please complete the following information):**
 - Device: [iPhone X]
 - OS: [iOS 13.2.2]
 - Package Manager used to install Lynx: [Zebra, Cydia, Installer]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.0.3]
 - Jailbreak Used: [Checkra1n, unc0ver]

**Additional context**

**Comment by MTACS** [comment]
Make sure you’re on the latest version of Lynx, it was a bug with AppList
