### ISSUE TITLE
App Switcher

### ISSUE THREAD

**Issue by Ahplla** [MTACS/Lynx#211]
Feature: Swipe to Kill

1. What does the slider mean?  (highlighted in the image)

![sample](https://i.ibb.co/nw0JRXL/F90-F3584-5042-4350-963-C-E1-B96-D602-B07.jpg)

2. The useless warning if you really want to close all apps, does not rotate according to the screen.  In fact, anyone who needs a warning for Swipe to Kill shouldn't be jailbroken. 

![Swipe Error](https://i.ibb.co/jTdk25M/F30491-AD-0-F9-E-4263-86-E6-10-DC7-EFB778-F.jpg)

**Comment by Ahplla** [comment]
Are you serious? I ask what for the slider is, no answers?

**Comment by MTACS** [comment]
I was cleaning issues and didn't mean to close it, it's the velocity to pull down to kill. I removed the alert in the next version
