### ISSUE TITLE
The Arabic language has disappeared!!

### ISSUE THREAD

**Issue by xFAHDx** [MTACS/Lynx#228]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**iDevice Information (please complete the following information):**
 - Device: [iPhone X]
 - OS: [iOS 13.2.2]
 - Package Manager used to install Lynx: [Zebra, Cydia, Installer]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.0.3]
 - Jailbreak Used: [Checkra1n, unc0ver]

**Additional context**

**Comment by xFAHDx** [comment]
It was available in the Arabic language version 1.2.7

**Comment by MTACS** [comment]
It has been temporarily removed as I’m working on a way to do translations that doesn’t require as much work, and can have up to date strings with ever version
