### ISSUE TITLE
Settings not work when toggled only

### ISSUE THREAD

**Issue by robmartin1987** [MTACS/Lynx#235]
**Describe the bug**
A clear and concise description of what the bug is. Go in to system wide enable modern table views 

**To Reproduce**
Steps to reproduce the behavior: downgraded to lowest available and nothing worked for me on 13.3 not now on a fresh jail broken 13.4.1 

**Expected behavior**
A clear and concise description of what you expected to happen. Settings toggle has no effect 

**Screenshots** first one is on 13.3 with modern style table togged on second two is on 13.4.1 toggled on with no effect. 
If applicable, add screenshots to help explain your problem.![image](https://user-images.githubusercontent.com/36098312/82252372-cfb92800-9946-11ea-8601-07adc670c3a1.jpeg) ![image](https://user-images.githubusercontent.com/36098312/82252403-d8116300-9946-11ea-8b7e-460e499c5a77.png) ![image](https://user-images.githubusercontent.com/36098312/82252425-e19acb00-9946-11ea-97c4-8496ac9a8d9c.png)

**iDevice Information (please complete the following information):**
 - Device: [iphone 7]
 - OS: [iOS 13.4.1]
 - Package Manager used to install Lynx: [Zebra]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.0.3] 1.3-1
 - Jailbreak Used: [Checkra1n, unc0ver] checkra1n 

**Additional context**

**Comment by MTACS** [comment]
Which options aren't working?

**Comment by robmartin1987** [comment]
The modern table cell for settings

**Comment by robmartin1987** [comment]
Fixed in latest update. Thank you sir.
