### ISSUE TITLE
Apps battery info in settings 

### ISSUE THREAD

**Issue by couchback** [MTACS/Lynx#240]
Battery info in settings won’t show up show continuely searching

**iDevice Information (please complete the following information):**
 - Device: [iPhone X]
 - OS: [iOS 13.2.2]
 - Package Manager used to install Lynx: [Zebra, Cydia, Installer]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.0.3]
 - Jailbreak Used: [Checkra1n, unc0ver]

**Additional context**

**Comment by MTACS** [comment]
Use a tweak such as Choicy to disable tweak injection into powerloghelperd daemon or powerloghelperdfix tweak to fix it, it's caused by substrate/substitute and not Lynx
