### ISSUE TITLE
Before 3 or 4 updates, the languages ​​have disappeared. Thank you

### ISSUE THREAD

**Issue by floranss** [MTACS/Lynx#241]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**iDevice Information (please complete the following information):**
 - Device: [iPhone X]
 - OS: [iOS 13.2.2]
 - Package Manager used to install Lynx: [Zebra, Cydia, Installer]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.0.3]
 - Jailbreak Used: [Checkra1n, unc0ver]

**Additional context**

**Comment by MTACS** [comment]
This is due to manual translations being out of date, I am moving to another localization platform and language support will reappear in a future update
