### ISSUE TITLE
Clock Font Style Bug

### ISSUE THREAD

**Issue by anonfox9** [MTACS/Lynx#253]
**Describe the bug**

Under Lockscreen > Clock Font Style.
I’m assuming this is the font size of the time. If so, changing to any number does nothing.

**To Reproduce**

Enter any number, no change in lockscreen time text size.

**Expected behavior**

Change size.

**Screenshots**

**iDevice Information (please complete the following information):**
 - Device: [iPhone X]
 - OS: [iOS 13.5]
 - Package Manager used to install Lynx: [Cydia]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.3]
 - Jailbreak Used: [unc0ver]

**Additional context**

**Comment by MTACS** [comment]
Turn on use custom font weight below it, I’ll rework the logic for it in the next update, I guess it’s checking if that’s enabled

**Comment by anonfox9** [comment]
Ah yes, thank you :D I can enable and leave default. A little confusing but thanks maybe a different switch of auto enable if it isn’t set to default 80 :D thanks again
