### ISSUE TITLE
Hide dock background isnt working 

### ISSUE THREAD

**Issue by rodainas** [MTACS/Lynx#257]
Hide dock background isnt working 
**iDevice Information (please complete the following information):**
 - Device: [iPhone XR]
 - OS: [iOS 13.5]
 - Package Manager used to install Lynx: [Cydia]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.3]
 - Jailbreak Used: [, unc0ver]

**Additional context**

**Comment by kegobass** [comment]
I am also having this issue.

Device: [iPhone X]
OS: [iOS 13.5]
Package Manager used to install Lynx: [Zebra]
Lynx Version (Can be found at the bottom of Settings pane): [1.3]
Jailbreak Used: [, unc0ver]
