### ISSUE TITLE
Lynx and Intelligentpass 3 conflict

### ISSUE THREAD

**Issue by struo** [MTACS/Lynx#258]
**Describe the bug**
There is a conflict with both tweaks installed. Adding the known WIFI and Bluetooth option in intelligentpass 3, the passcode and face ID is always prompted. 

**To Reproduce**
Both tweaks must be installed. A known WIFI or bluetooth must be added. There are no configurations on Lynx. Lynx must be installed. 

**Expected behavior**
I expected adding a known WIFI with Lynx installed would not present a passcode and the face ID lock.

**iDevice Information (please complete the following information):**
 - Device: [iPhone 11 Pro]
 - OS: [iOS 13.5]
 - Package Manager used to install Lynx: [Zebra]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.3.-4]
 - Jailbreak Used: [unc0ver]

**Additional context**
I installed icleaner pro and disabled Lynx with intelligentpass 3 installed. Once disabling Lynx, the known wifi option worked and did not present a passcode or face ID. Enabling Lynx again in icleaner presents the same issue (face ID and passcode comes up)

**Comment by ghysler** [comment]
Don't want to hijack this issue, but thought this might be useful info for debugging and other people experiencing this conflict:

For me the issue described by @struo above _only_ occurs when I use Lynx to disable the lockscreen camera access (swipe). I can not reproduce this issue after enabling the lockscreen camera access again using Lynx (switch off). Same issue also occurs when using other ways (e.g. Flex tweaks) to disable the lockscreen camera access. This makes me think this is actually a bug in IntelligentPass 3 instead, but perhaps the creator of Lynx could shine some light on this.

**iDevice Information (please complete the following information):**

    Device: [iPhone X]
    OS: [iOS 13.5]
    Package Manager used to install Lynx: [Cydia]
    Lynx Version (Can be found at the bottom of Settings pane): [1.3.-4]
    Jailbreak Used: [checkra1n]

**Comment by MTACS** [comment]
I'll purchase the tweak today and do some digging, not quite sure what methods and stuff it uses, so it's hard to say what is the cause of the issue. I'll try to get a solution either way as soon as I can

**Comment by MTACS** [comment]
Didn't mean to hit close

**Comment by MTACS** [comment]
From what I can tell it has to do with a global hook that allows certain functions like the camera. I'll reach out to them, as I'm not sure there's much I'll be able to do on my end

`%hook SBMainDisplayPolicyAggregator

- (BOOL)_allowsCapabilityLockScreenCameraWithExplanation:(id*)arg1 {

	return !hideLockscreenCamera;

}

%end`

**Comment by ghysler** [comment]
Thanks a lot for your efforts @MTACS ! :+1:
