### ISSUE TITLE
Show done button 

### ISSUE THREAD

**Issue by rodainas** [MTACS/Lynx#269]
**Describe the bug**
The Show Done Button in Icon settings, whenever you enable or disable has no effect, the button is always shown.

**iDevice Information (please complete the following information):**
 - Device: [iPhone XR]  
 - OS: [iOS 13.5]
 - Package Manager used to install Lynx: [Zebra]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.4-2]
 - Jailbreak Used: [unc0ver]

**Comment by MTACS** [comment]
Fixed in 1.4-4
