### ISSUE TITLE
Laggy app switcher 

### ISSUE THREAD

**Issue by stancruzsolo** [MTACS/Lynx#272]
**Describe the bug**
The new update just made the app switcher so laggy and unresponsive.

**To Reproduce**
Open couple of apps
Open app switcher and scroll slowly
Try closing the apps, the animations are super slow and feels laggy

**Expected behavior**
What I expected was a natural gestures behaviour especially on stable build of iOS 13.5

**Screenshots**
Cannot screenshot the animations

**iDevice Information (please complete the following information):**
 - iPhone 6s
 - iOS 13.5
 - Cydia
 - 1.4-2
 - unc0ver

**Additional context**
Nothing more

**Comment by MTACS** [comment]
Fixed in 1.4-3 just waiting for it to be live on Twickd
