### ISSUE TITLE
Disable springboard rotation

### ISSUE THREAD

**Issue by rodrigomc2000** [MTACS/Lynx#278]
**Is your feature request related to a problem? Please describe.**

Yes, the rotation lock that exist on iOS works perfect but I always keep this feature disabled because in some apps or playing videos I need to use the rotate feature but if I’m at the home or any page of springboard it will also rotate the screen if I rotate my iPhone and icons of my theme mess up !

**Describe the solution you'd like**

Add an option to lock the phone orientation to vertical in whole springboard 

**Describe alternatives you've considered**

Said above 

**Additional context**

I purchase your tweak and is awesome ! An must have for every jailbreak user !

**Comment by MTACS** [comment]
Added in 1.4-4
