### ISSUE TITLE
Remove screenshot sound 

### ISSUE THREAD

**Issue by rodrigomc2000** [MTACS/Lynx#279]
**Is your feature request related to a problem? Please describe.**

Yes, this sound is annoying and sometimes we don’t wanna listen this sound 

**Describe the solution you'd like**

Option to disable the screenshot and video record sound without need to use the mute iPhone button

**Describe alternatives you've considered**

There’s already separate tweaks that do this job but if you add in lynx it will be more completed 

**Additional context**

Thank you

**Comment by MTACS** [comment]
What is the issue? Is disabling screenshot sound not working for you?

**Comment by rodrigomc2000** [comment]
I've found just "disable shutter sound" on photos in your tweak! It will disable the photo sound after take a picture... but the screenshot sound still playing... and record video sounds too!

Thanks!

**Comment by DemoJameson** [comment]
> I've found just "disable shutter sound" on photos in your tweak! It will disable the photo sound after take a picture... but the screenshot sound still playing... and record video sounds too!
> 
> Thanks!

You should enable `System Wide` -> `Disable Screenshot Sound` too.
