### ISSUE TITLE
Disable Auto Lock option does not work

### ISSUE THREAD

**Issue by JoeWells1** [MTACS/Lynx#280]
![AC4BAF2B-8144-40AD-9927-F294C031A786](https://user-images.githubusercontent.com/66459272/83844578-e0022e80-a6cc-11ea-8cf5-af9c68a82f28.jpeg)
Hello friend, I wanted to inform you of an error about the Lynx configuration, it happens that the option "Deactivate automatic lock in low consumption mode" does not allow me to activate it, the button is there but it does not allow me to change the option. I would appreciate if you can resolve it as soon as possible as this is one of the main options for which I bought this license, have a nice day.

**Comment by MTACS** [comment]
I have it disabled as I'm working on a more efficient way for this to work, I'll update it when it's working properly
