### ISSUE TITLE
Incompatible with killx pro

### ISSUE THREAD

**Issue by sm00thcr1m1nal6** [MTACS/Lynx#290]
**Describe the bug**
Whenever lynx is enabled, one feature of killx pro doesn’t work - that is, locking apps to prevent them from closing when otherwise closing all apps.

**To Reproduce**

**Expected behavior**

**Screenshots**

**iDevice Information (please complete the following information):**
 - Device: [iPhone X]
 - OS: [iOS 13.2.2]
 - Package Manager used to install Lynx: [Zebra, Cydia, Installer]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.0.3]
 - Jailbreak Used: [Checkra1n, unc0ver]

**Additional context**

**Comment by tychoregter** [comment]
Yeah. That one is pretty annoying, I hope it can be fixed soon

**Comment by tychoregter** [comment]
Maybe, when the 3D Touch to kill option is disabled you could completely disable the 3D touch in the switcher
