### ISSUE TITLE
Broken camera button on lockscreen

### ISSUE THREAD

**Issue by chubguard** [MTACS/Lynx#295]
**Describe the bug**
The camera shortcut button on my lockscreen is greyed out and I cannot press it.

**To Reproduce**
This started after I installed lynx, while already having QuickLS installed. I uninstalled QuickLS and am still having the problem.

**Expected Behavior**
The camera shortcut on the lockscreen will be greyed out and unusable.

**Screenshots**
https://imgur.com/a/pVdjl7z

**iDevice Information (please complete the following information):**
 - Device: [iPhone XS Max]
 - OS: [iOS 13.3]
 - Package Manager used to install Lynx: [Cydia]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.3]
 - Jailbreak Used: [unc0ver]

**Additional context**

**Comment by MTACS** [comment]
Do you have 'disable camera swipe' enabled under Lockscreen?

**Comment by chubguard** [comment]
I did indeed, thanks!

**Comment by MTACS** [comment]
No problem! If you want it disabled but still want to use the camera, turn on the force enable camera option.
