### ISSUE TITLE
Enable lynx make pagedot more invisible

### ISSUE THREAD

**Issue by DemoJameson** [MTACS/Lynx#299]
**Describe the bug**
Enable lynx make pagedot more invisible.

**To Reproduce**
Install lynx and enable it.

**Expected behavior**
Don't change the transparency of pagedot.

**Screenshots**
before
![image](https://user-images.githubusercontent.com/181192/84344101-7dcd9000-abdc-11ea-860e-924b16059ff1.png)

after
![image](https://user-images.githubusercontent.com/181192/84344183-aa81a780-abdc-11ea-935c-778ad482fbc6.png)

**iDevice Information (please complete the following information):**
 - Device: [iPhone 7P]
 - OS: [iOS 13.5.0]
 - Package Manager used to install Lynx: [Zebra]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.3]
 - Jailbreak Used: [Checkra1n]

**Comment by alienjax** [comment]
Can confirm having the same issue. 

iPhone 6s
iOS 13.5
Installed via Sileo
Unc0ver jailbreak 
Lynx version 1.3

**Comment by MTACS** [comment]
Fixed in 1.5
