### ISSUE TITLE
Settings crashes when opening SpringBoard settings

### ISSUE THREAD

**Issue by Sxooter7je** [MTACS/Lynx#3]
**Describe the bug**
Settings.app crashes when opening the SpringBoard tab

**To Reproduce**
Open Settings, navigate to Lynx, press SpringBoard

**Expected behavior**
I expect the tweak to open the SpringBoard settings pane

**Screenshots**
I don’t think this is needed.

**iDevice Information (please complete the following information):**
 - Device: iPhone 8+
 - OS: iOS 13.2.3
 - Package Manager used to install Lynx: Cydia
 - Lynx Version (Can be found at the bottom of Settings pane): 1.0.5

**Additional context**
N.A.

**Comment by MTACS** [comment]
Please make sure you have the latest version of Cephei (1.14) from Chariz and libcolorpicker (1.6.5) from BigBoss installed
