### ISSUE TITLE
Makes my device freeze sometimes after a respring 

### ISSUE THREAD

**Issue by El-MokoMoko** [MTACS/Lynx#30]
Sometimes after respring my widgets (Xen Html) take longer to load and after unlock i got a freeze of 1 minutes and leads to a respring once again.
I disabled it via iCleaner Pro and no issue after that.
It seems to be a memory leak.

**iDevice informations**
 - Device: [iPhone X]
 - OS: [iOS 13.3]
 - Package Manager used to install Lynx [Cydia]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.0.8]

**Comment by MTACS** [comment]
Could I please get a full list of packages installed

**Comment by El-MokoMoko** [comment]
Here my tweaklist : https://pastebin.com/VNFeQ2Qq

**Comment by BaddestAssasin** [comment]
This also happened to me

**Comment by MTACS** [comment]
Could I get a list of tweaks installed, and whether it happens when just
Lynx is enabled? Very hard to solve without knowing the whole situation

**Comment by BaddestAssasin** [comment]
Only when lynx is enabled and tweaks like smooth lock x and primal folders that lynx already tweaks where installed after I uninstalled lynx

**Comment by BaddestAssasin** [comment]
https://pastebin.com/vM6y2s0X
