### ISSUE TITLE
Disable status bar battery animation

### ISSUE THREAD

**Issue by Laiteux** [MTACS/Lynx#306]
**Is your feature request related to a problem? Please describe.**
Would be something nice, I don't really like to have this animation.

**Describe the solution you'd like**
A way to disable this status bar animation when plugging my phone to charge

![image](https://user-images.githubusercontent.com/33204743/84570155-0b46e680-ad7b-11ea-98da-cfa8b3126bcd.jpeg)

**Comment by camillionaire7** [comment]
Digitalbattery13 has this feature. Select Apple method (stock) if you’re using a different battery icon tweak.

**Comment by Laiteux** [comment]
Looks like my email reply didn't get through, so I'll copy paste it here:

Thanks a lot for the suggestion. However, I don't wanna use this tweak.
The less tweaks the best, and a simple toggle in Lynx would be amazing.
I will most likely wait for Lynx to implement this as a feature.

(:
