### ISSUE TITLE
Hide widget page footer

### ISSUE THREAD

**Issue by Laiteux** [MTACS/Lynx#308]
**Is your feature request related to a problem? Please describe.**
It annoys me to have this useless widget page footer text about where the meteo data is coming from.

**Describe the solution you'd like**
A toggle to hide it would be amazing.

![image](https://user-images.githubusercontent.com/33204743/84570255-cec7ba80-ad7b-11ea-8a80-050692fdd2df.jpeg)

**Comment by MTACS** [comment]
C'est déjà possible avec Lynx > Today View > 'Hide Weather Info Text'

**Comment by Laiteux** [comment]
Ahhh, c'est donc ça que t'appelle today view! Merci beaucoup
