### ISSUE TITLE
Passcode screen digits left on the screen after unlocking phone with FaceID

### ISSUE THREAD

**Issue by Laiteux** [MTACS/Lynx#309]
**To Reproduce**
1. Turn your phone/lockscreen ON
2. Swipe up in order to show the passcode screen
3. Don't touch anything but unlock your phone using FaceID
3. Your phone will get unlocked but the passcode digits will stay at the top of the screen for a second or so (see screenshot above)

**iDevice Information (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 13.5
 - Package Manager used to install Lynx: Zebra
 - Lynx Version (Can be found at the bottom of Settings pane): 1.5
 - Jailbreak Used: unc0ver

**Screenshots**
![Screenshot](https://share.laiteux.dev/xruicvig)

Plein d'amour

**Comment by MTACS** [comment]
Fixé dans la dernière mise à jour
