### ISSUE TITLE
Date as carrier not showing

### ISSUE THREAD

**Issue by alienjax** [MTACS/Lynx#314]
**Describe the bug**
“Use date as carrier” will only show date if “Use custom carrier” is on AND a custom string has been entered for carrier. 

**iDevice Information (please complete the following information):**
 - Device: [iPhone 6s]
 - OS: [iOS 13.5]
 - Package Manager used to install Lynx: [Sileo]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.5]
 - Jailbreak Used: [ unc0ver]

**Additional context**

**Comment by MTACS** [comment]
Fixed
