### ISSUE TITLE
Lockscreen Alighment Bug; Conflict with Colorfulnotifs

### ISSUE THREAD

**Issue by whiteblacksmiths** [MTACS/Lynx#316]
**Describe the bug**

1.5-1 broke the recently-fixed lockscreen clock alignment in 1.5. it also caused a tweak conflict with another tweak colorfulnotif by @neoney_ on twitter, causing springboard to crash every time a notification is received. downgrading back to 1.5 solves both issues

**To Reproduce**
to reproduce the springboard crash with colorfulnotif, just send a notification to device. 

**Screenshots**
no screenshots, but this is the crashlog.
https://pastebin.com/HgmHVBKD

**iDevice Information (please complete the following information):**
 - Device: [iPhone X]
 - OS: [iOS 13.5]
 - Package Manager used to install Lynx: [Zebra]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.5–1]
 - Jailbreak Used: [unc0ver]

**Comment by MTACS** [comment]
Fixed
