### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by dinouse** [MTACS/Lynx#324]
**Describe the bug**
Disable Icon darkening not working

**Expected behavior**
The icon just keep darkening

**Screenshots**
![image](https://user-images.githubusercontent.com/62304158/84697349-90e7b380-af80-11ea-9dae-9d80f85024f2.png)

**iDevice Information (please complete the following information):**
 - Device: iPhone 6s
 - OS: 13.3
 - Package Manager used to install Lynx: Cydia
 - Lynx Version (Can be found at the bottom of Settings pane): 1.5
 - Jailbreak Used: Checkra1n

**Comment by MTACS** [comment]
It’s currently only for screentime, if it’s appearing when tapping, there is an option in Snowboard to disable it, I’ll add it eventually
