### ISSUE TITLE
More ‘settings’ Customization

### ISSUE THREAD

**Issue by PEAR5EY** [MTACS/Lynx#332]
If you could incorporate things like, rounded corners, no black line, basically what iKSprefs lets you do for settings... means another tweak we could let go off.

And then jellyfish and finger lock... you would have it all locked down in one easy to use app. AMAZING!

![B1588856-DAE9-4E56-BF8B-2BFB44EC3482](https://user-images.githubusercontent.com/66477712/85032906-40d34180-b178-11ea-8eee-79d642cbafe0.jpeg)

**Comment by MTACS** [comment]
You can already do the rounded corners by selecting the app in Lynx > System Wide > Modern table cells, and the option to hide the black line is in the same section under navigation bars. As for incorporating tweaks like jellyfish or FingerLock I’ll most likely not add them as they’re already separate
