### ISSUE TITLE
Smaller Steps on Dock Icon Scaling

### ISSUE THREAD

**Issue by tuskiie** [MTACS/Lynx#334]
Is it possible to have smaller steps on the dock icon scaling? 1 is too small for me and 2 is too big and I can’t choose an in between.

**Comment by MTACS** [comment]
If you long press on the slider it’ll let you input a custom value

**Comment by tuskiie** [comment]
For me after I input 1.5 it just puts it to 2.

**Comment by tuskiie** [comment]
> If you long press on the slider it’ll let you input a custom value
> On Jun 18, 2020, 6:18 PM -0400, creepercardz <notifications@github.com>, wrote:
> > Is it possible to have smaller steps on the dock icon scaling? 1 is too small for me and 2 is too big and I can’t choose an in between.
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 


For me after I input 1.5 it just puts it to 2.

**Comment by MTACS** [comment]
Just looked over it, it will automatically round to the nearest whole number as I have it set to scale by 10% increments, I'll add a smaller change percentage

**Comment by tuskiie** [comment]
Thanks a ton.
