### ISSUE TITLE
Double tap to lock

### ISSUE THREAD

**Issue by PEAR5EY** [MTACS/Lynx#336]
**Describe the bug**

When ‘double tap to lock’ is on, and then I ‘edit home screen‘ and I double tap the apps icon to change it, snowboard function, it obvs locks the phone and makes this function on snowboard redundant. 

**To Reproduce**

Have snowboard installed. Go into ‘edit home screen’ mode and double tap an icon, which would normally open up snowboard so you can change an icons design. Instead it locks the iPhone.

**iDevice Information (please complete the following information):**
 - Device: XR
 - OS: iOS 13.5
 - Package Manager used to install Lynx: Zebra 1.2 beta 1b
 - Lynx Version (Can be found at the bottom of Settings pane): 1.5
 - Jailbreak Used: unc0ver

**Additional context**
FIX: ‘Double tap to lock’, needs to disable itself when ‘edit home screen’ is activated.

Thanks for the tips on my last query, much appreciated, Lee

**Comment by MTACS** [comment]
I'll add a check to make sure it is not activated when editing icons
