### ISSUE TITLE
Remove app icon and title from today view widgets

### ISSUE THREAD

**Issue by MistryM4chine** [MTACS/Lynx#339]
**Is your feature request related to a problem? Please describe.**
The problem is that the app icon and app title on the today view widgets looks quite ugly and would look better without it. 

**Describe the solution you'd like**
Please could you try and add and option that removes the app icon and app title from the top of today view widgets? Thank you :)

**Describe alternatives you've considered**
I have tried the tweak better widgets to try achieve this, but it made my device device buggy. 

**Additional context**
Here is a screenshot of the part that I would like to remove. 
![2FE63815-9C58-42C3-8BD5-B501916D89CA](https://user-images.githubusercontent.com/57872364/85233809-1942da00-b401-11ea-86cb-ce2f9e967c00.jpeg)

**Comment by MTACS** [comment]
I'll add it in the next update
