### ISSUE TITLE
Toggle to hide AM/PM label After the time in the status bar

### ISSUE THREAD

**Issue by Remdog1997** [MTACS/Lynx#340]
**Is your feature request related to a problem? Please describe.**

I think the status bar looks less cluttered without the AM/PM label. I also think it’s redundant because it’s hard to mix up whether it’s the morning or the afternoon.

**Describe the solution you'd like**

When the toggle is pressed, the AM/PM label disappears and the time is centered in the status bar.

**Describe alternatives you've considered**

**Additional context**

**Comment by MTACS** [comment]
Added option to set a custom date format in 1.5.1 
![image](https://user-images.githubusercontent.com/13209789/86057246-d5695980-ba2c-11ea-87d2-d4aa5569ec67.png)
