### ISSUE TITLE
Disable status bar charging animation 

### ISSUE THREAD

**Issue by camillionaire7** [MTACS/Lynx#348]
**Is your feature request related to a problem? Please describe.**
No it’s not related to a problem 

**Describe the solution you'd like**
Option to hide the status bar charging animation when phone is plugged in

**Additional context**
![A648FE18-DF3B-4B3D-BDEA-7EBFA57C4C1E](https://user-images.githubusercontent.com/67725715/86318012-b4983400-bbe5-11ea-807e-a2723ac65c02.jpeg)

[Reddit post about this, with video](https://www.reddit.com/r/jailbreak/comments/hjnx0h/question_anyone_know_how_to_remove_the_status_bar/?utm_source=share&utm_medium=ios_app&utm_name=iossmf)

**Comment by Laiteux** [comment]
#306
