### ISSUE TITLE
Bugs report

### ISSUE THREAD

**Issue by amiruzl** [MTACS/Lynx#35]
1. Cant drag app icon when editing homescreen, if lynx disable the app icon can move again
2. No notification text option not working, already enable it and still showing in NC
3. Youtube Stories, stories still showing even the option is already enable
![BD38E059-5965-46B4-8CF1-062C5A95A20A](https://user-images.githubusercontent.com/25230530/73313217-2e09b000-425d-11ea-81e0-1bf8eff5811c.png)
4. Notification Corner Radius not working

**iDevice Information
 - Device: [iPhone X]
 - OS: [iOS 13.3]
 - Package Manager used to install Lynx [Zebra]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.1.1]

**Comment by MTACS** [comment]
Fixed Notification Center hiding, Notification Corner radius should work if toggle is enabled, and removed hiding stories until I can figure out a better way to hide them. Icon moving seems to be a conflict with another tweak, I'll look into that

**Comment by amiruzl** [comment]
Nope, corner radius defenetly not work for me

**Comment by MTACS** [comment]
It only works with Modern Notification style is enabled

**Comment by amiruzl** [comment]
No its not. Even lynx messing up jellyfish now 
I set it to five then zero no different 
![79A92F3A-92DD-4930-AE87-F056E6A92D20](https://user-images.githubusercontent.com/25230530/73317856-2dc3e180-426a-11ea-8fc4-70d2c2240893.png)
![Uploading 01F3682F-B88F-4F44-B844-596CD3FD0351.png…]()

**Comment by MTACS** [comment]
Does it work with any icon radius set?
![IMG_35B26E289211-1](https://user-images.githubusercontent.com/13209789/73318064-41d5f780-4206-11ea-8633-3644f3e2d6c7.jpeg)

**Comment by amiruzl** [comment]
No it doesn't , tried set it from zero to five but it all look the same 
![EC18025C-7147-42CA-B3EF-70BB984CDC67](https://user-images.githubusercontent.com/25230530/73318159-26510800-426b-11ea-80ca-aa49daaab805.png)

**Comment by MTACS** [comment]
Does it work set all the way to 17?

**Comment by amiruzl** [comment]
The only thing got changed is the icon get circle if set to 17
![441973F4-2ECB-46CA-B5B0-189000F1C016](https://user-images.githubusercontent.com/25230530/73318417-eb9b9f80-426b-11ea-8e1c-6d35624dc47e.png)
