### ISSUE TITLE
Screenshot preview 

### ISSUE THREAD

**Issue by TurtleTurtles** [MTACS/Lynx#354]
While we have the disable screenshot sound or the flash, another option to be added would be screenshot preview disabled. In the tweak mikoto from Karen. She has that option but I just don’t wanna have that tweak just for one feature if Lynx can have it too. Appreciate it mate.

**Comment by MTACS** [comment]
Just added it to 1.6, expect an update soon :)

**Comment by TurtleTurtles** [comment]
Ayyy thanks mate.
