### ISSUE TITLE
Option to remove the CarPlay indicator from the status bar

### ISSUE THREAD

**Issue by Remdog1997** [MTACS/Lynx#359]
**Is your feature request related to a problem? Please describe.**

When CarPlay is enabled, a status indicator appears in the status bar. 

**Describe the solution you'd like**

When the toggle is enabled, the CarPlay symbol disappears from the status bar 

**Describe alternatives you've considered**

**Additional context**

**Comment by MTACS** [comment]
Added in 1.6
