### ISSUE TITLE
Lynx -> Phone -> Use large button conflict with CallbarXS

### ISSUE THREAD

**Issue by Michael1999US** [MTACS/Lynx#36]
**Describe the bug**
I can't use large call button due to conflict with callbarxs version 2.3-75
**To Reproduce**
Turn ”use large button” in the phone section. Call to someone. 

**Expected behavior**
To have a large button just in the phone app or when on fullscreen mode.
**Screenshots**
![A5B3ED75-24AD-4D76-8FC6-B433A10E7262](https://user-images.githubusercontent.com/56358359/73313299-27624500-422b-11ea-8522-16bd6fe40448.png)
![AA2DF2B5-3B0C-4554-96C5-75AB28EEAA6C](https://user-images.githubusercontent.com/56358359/73313300-27624500-422b-11ea-805a-764f6db6474f.png)

**iDevice Information (please complete the following information):**
 - Device: [iPhone 6s Plus]
 - OS: [iOS 13.3]
 - Package Manager used to install Lynx [Cydia]
 - Lynx Version [1.1.1]

**Additional context**
[None]

**Comment by MTACS** [comment]
Please disable that option until I can buy CallbarXS and try to detect the view
