### ISSUE TITLE
Hoping you’ll add 

### ISSUE THREAD

**Issue by andveg38** [MTACS/Lynx#364]
**Is your feature request related to a problem? Please describe.**

No problem. 

**Describe the solution you'd like**

Can you add?:
- disable spotlight on lock screen
- hide screen time timeout hourglas
- hide stock widget footer 

**Describe alternatives you've considered**

**Additional context**
Thanks for considering!!

**Comment by MTACS** [comment]
1. Spotlight: Are you talking about the one at the top of the widgets page? 2: ScreenTime hourglass is under Lynx > System Wide > ScreenTime > Disable Hourglass Icon. 3 Hide stock widget footer: Lynx > Today View > Hide Weather Info Text & Hide 'New Widgets' Button, but if anything isn't working please let me know and I'll try to get it fixed ASAP

**Comment by andveg38** [comment]
1. I am, yes. 
2. Oh, geez. I missed that option on screentime. Perfect. 
3. Last time I used the stocks app widget, it added info in the footer. This is what I was mentioning and wasn't clear. 

Thanks for replying!
