### ISSUE TITLE
Delete photo immediately does not work with 6S+, IOS 13.3.1

### ISSUE THREAD

**Issue by Xador123** [MTACS/Lynx#38]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**iDevice Information (please complete the following information):**
 - Device: [iPhone X]
 - OS: [iOS 13.2.2]
 - Package Manager used to install Lynx [Zebra, Cydia, Installer]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.0.3]

**Additional context**

**Comment by MTACS** [comment]
I changed the label to 'Skip deletion confirmation' until I can add the feature properly
