### ISSUE TITLE
minor bug regarding the "clear badges" text in the 3d touch menu

### ISSUE THREAD

**Issue by TheUltimateSike** [MTACS/Lynx#386]
**Describe the bug**
"clear badges" showing up in the 3d touch menu although there are no badges

**To Reproduce**
1: have a badge on an app
2: turn off notifications for that app via settings
3: "clear badges" will still show up

**Expected behavior**
"clear badges" should disappear

**Screenshots**
I‘ve uploaded a video to imgur https://imgur.com/a/MDjsX5I

**iDevice Information (please complete the following information):**
 - Device: [iPad mini 5]
 - OS: [iOS 13.5]
 - Package Manager used to install Lynx: [Zebra]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.6]
 - Jailbreak Used: [unc0ver]

**Additional context**

Edit: consistent through respring and ldrestart

Btw Lynx is a great tweak :D

**Comment by MTACS** [comment]
Thanks a bunch for pointing this out, I didn't even think of checking for that. I'll see if I can find something that tells me if notifications are on or not and go from there

**Comment by TheUltimateSike** [comment]
Always glad to help :)

**Comment by MTACS** [comment]
So unfortunately I can't find any built in methods that tell me if an app has notifications enabled yet, so sadly I don't know if it'll be in the next update. However I'm working on a way to check but it may take a little longer than I thought. I'll add the list tag to this to make sure it's top priority.

**Comment by TheUltimateSike** [comment]
Thanks for making the bug top priority, but you really don‘t have to :).
I‘m sure there are other bugs / feature requests / stuff in your real life
that are more important. Do what you want though :)
