### ISSUE TITLE
3D touch icon color for clear badges is only white

### ISSUE THREAD

**Issue by stancruzsolo** [MTACS/Lynx#395]
**Describe the bug**
3D Touch icon for “clear badges” is only in white color

**To Reproduce**
Simply invoke 3D Touch or haptic menu on an app with badges

**Expected behavior**
It should display white icon for dark appearance and dark icon for light appearance.

**Screenshots**

![926D811B-771B-462C-86F8-13957618C3D8](https://user-images.githubusercontent.com/61632739/90371715-ffceaf00-e08c-11ea-9cc6-d22df73d10fb.png)

![BF8B57C9-D024-4147-9AD5-1F1132425334](https://user-images.githubusercontent.com/61632739/90371695-f47b8380-e08c-11ea-8b6e-137ba13b4fcd.png)

**iDevice Information (please complete the following information):**
 - Device: iPhone 8 and iPad Pro 10.5
 - OS: iOS 13.6
 - Package Manager used to install Lynx: Sileo
 - Lynx Version (Can be found at the bottom of Settings pane): 1.7
 - Jailbreak Used: checkra1n/odysseyra1n 

**Additional context**
Would love to see it match iOS light appearance.

**Comment by MTACS** [comment]
Must've overlooked it, I haven't used light mode since the day 13 came out. Fixed in 1.7.1
