### ISSUE TITLE
Lynxprefs.bundle error after re-jailbreak

### ISSUE THREAD

**Issue by PEAR5EY** [MTACS/Lynx#396]
**Describe the bug**
There was an error loading the preference bundle for Lynx: The Bundle “lynxprefs.bundle” couldn’t be loaded because it is damaged or missing necessary resources.

**To Reproduce**
Use uncover and reinstall the rootfs.
Then re-jailbreak using uncover.
Use batchomatic to install all repo and tweaks.
Done.

**Expected behavior**
Lynx now won’t open. Reinstalled and deleted and installed. No joy

**Screenshots**
Screenshot attached.

**iDevice Information (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 13.5
 - Package Manager used to install Lynx: Zebra
 - Lynx Version 1.7
 - Jailbreak Used: uncover

**Additional context**

**Comment by MTACS** [comment]
I'm assuming you already have Cephei installed? This is the only dependency that prefs rely on, maybe it didn't get installed when using Batchomatic? I've seen the error a few times, but can never reproduce it

**Comment by PEAR5EY** [comment]
Just reinstalled that dependency. Same error appears in Lynx 😬

Is there a cache I can empty as I thought deleting Lynx and reinstalling would fix any bad links or corrupt folder issues.

I can see the folder is there using FileZilla, so it’s a strange one.

**Comment by PEAR5EY** [comment]
Just reinstalled that dependency. Same error appears in Lynx 😬

Is there a cache I can empty as I thought deleting Lynx and reinstalling would fix any bad links or corrupt folder issues.

I can see the folder is there using FileZilla, so it’s a strange one.

**Comment by PEAR5EY** [comment]
Just reinstalled that dependency. Same error appears in Lynx 😬

Is there a cache I can empty as I thought deleting Lynx and reinstalling would fix any bad links or corrupt folder issues.

I can see the folder is there using FileZilla, so it’s a strange one.

**Comment by PEAR5EY** [comment]
Just reinstalled that dependency. Same error appears in Lynx 😬

Is there a cache I can empty as I thought deleting Lynx and reinstalling would fix any bad links or corrupt folder issues.

I can see the folder is there using FileZilla, so it’s a strange one.

**Comment by PEAR5EY** [comment]
Just reinstalled that dependency. Same error appears in Lynx 😬

Is there a cache I can empty as I thought deleting Lynx and reinstalling would fix any bad links or corrupt folder issues.

I can see the folder is there using FileZilla, so it’s a strange one.

**Comment by PEAR5EY** [comment]
Just reinstalled that dependency. Same error appears in Lynx 😬

Is there a cache I can empty as I thought deleting Lynx and reinstalling would fix any bad links or corrupt folder issues.

I can see the folder is there using FileZilla, so it’s a strange one.

**Comment by PEAR5EY** [comment]
Just reinstalled that dependency. Same error appears in Lynx 😬

Is there a cache I can empty as I thought deleting Lynx and reinstalling would fix any bad links or corrupt folder issues.

I can see the folder is there using FileZilla, so it’s a strange one.

**Comment by PEAR5EY** [comment]
Just reinstalled that dependency. Same error appears in Lynx 😬

Is there a cache I can empty as I thought deleting Lynx and reinstalling would fix any bad links or corrupt folder issues.

I can see the folder is there using FileZilla, so it’s a strange one.

**Comment by PEAR5EY** [comment]
Just reinstalled that dependency. Same error appears in Lynx 😬

Is there a cache I can empty as I thought deleting Lynx and reinstalling would fix any bad links or corrupt folder issues.

I can see the folder is there using FileZilla, so it’s a strange one.

**Comment by PEAR5EY** [comment]
Just reinstalled that dependency. Same error appears in Lynx 😬

Is there a cache I can empty as I thought deleting Lynx and reinstalling would fix any bad links or corrupt folder issues.

I can see the folder is there using FileZilla, so it’s a strange one.

**Comment by PEAR5EY** [comment]
Literally word for word what I did above and the problem started. Why doesn’t deleting the app and reinstalling it fix the issue?

**Comment by PEAR5EY** [comment]
Hey... hello... I’ve paid for this app now I can’t use it. Can I get some help here. All I’ve done is re-jail broken my phone and restored a batchomatic back up for all apps and repos. Nothing out of the norm, and now Lynx don’t work no matter what I do.

**Comment by MTACS** [comment]
Try deleting all files that have com.mtac.lynx in /var/mobile/Library/Preferences, hope that'll help as this issue is strange and I cannot reproduce in any way

**Comment by PEAR5EY** [comment]
Tried that.
Deleted the app aswell.
Fresh install.

Still thinks the bundle file is currupt.

**Comment by PEAR5EY** [comment]
Even tried downgrading incase there was any confliction with the new version 1.7. No joy ether

**Comment by PEAR5EY** [comment]
What’s making it flag the error as everything has been deleted and reinstalled?!?
