### ISSUE TITLE
1.15.2 cephie update crashes Lynx

### ISSUE THREAD

**Issue by PEAR5EY** [MTACS/Lynx#405]
Device: [iPhone XR
 - OS: [iOS 13.5
 - Package Manager used to install Lynx:
Zebra
 - Lynx Version (Can be found at the bottom of Settings pane): [1.7.1
 - Jailbreak Used: unc0ver

**Comment by MTACS** [comment]
I see that it is now 1.15.3, does it still cause the same problems?

**Comment by PEAR5EY** [comment]
All fixed with 1.15.3.


Thanks,

Lee



On 25 Aug 2020, at 4:05 pm, MTAC <notifications@github.com> wrote:

﻿
I see that it is now 1.15.3, does it still cause the same problems?

**Comment by MTACS** [comment]
Glad to hear!
