### ISSUE TITLE
Hide Status Bar is wonky on last update

### ISSUE THREAD

**Issue by Chocapic** [MTACS/Lynx#408]
**Describe the bug**
I have Status Bar disabled on Homescreen + Locks screen (not hide everywhere). If you lock the iPhone while an app is running (and showing the SB), when you wake it the SB appears on the LS, and HS when you unlock it. Pulling down the notification center while on the HS will make the SB disappear again, even in apps despite hide everywhere not being toggled.

**To Reproduce**
- Toggle Hide SB on LS + HS(respring)
- Open any app with SB at the top
- Lock phone
- Wake it up
- Unlock
- Pull down notification center

**Expected behavior**
SB being always hidden on HS and LS and always showing in apps. 

**Device Information (please complete the following information):**
 - Device: iPhone 6s+
 - OS: iOS 13.4.1
 - Package Manager used to install Lynx: cydia
 - Lynx Version 1.7.1
 - Jailbreak Used: Checkra1n

**Additional context**
Happened after 1.7 update. No other tweak is interscting with the status bar. I uninstalled Indy just to make sure.

**Comment by MTACS** [comment]
It's the way I check if the current app is SpringBoard or the presented/unlocked notification center, I'll see if I can make it check sooner after locking/unlocking, thanks for pointing it out, I could see how it could get annoying. I'll see what I can do to get it to work

**Comment by MTACS** [comment]
Fixed in 1.8
