### ISSUE TITLE
"Hide Folder Icon Background" still not working

### ISSUE THREAD

**Issue by zibo29** [MTACS/Lynx#41]
I saw you marked it as fixed, still the same recurring bug - some folder has not the background, others have it, opening and closing that folder sometimes fixes it. In the end i have a mix of folders with no bakground, some with backgrounds. (i'm not talking about "open folder background"). 
Thanks!

iphone 7 plus 13.2.2
Lynx 1.1.1

**Comment by MTACS** [comment]
I’ll see if I can reproduce it, but I hid it with many different ways to
make sure it worked, after it kept reoccurring

**Comment by zibo29** [comment]
Let me know if I can help somehow!
