### ISSUE TITLE
Ability to Hide Search Bar in Today View

### ISSUE THREAD

**Issue by ZenIsBestWolf** [MTACS/Lynx#411]
**Is your feature request related to a problem? Please describe.**
No, I just find the search bar ugly when using Kalm with the Today View on the lock screen.
**Describe the solution you'd like**
A toggle which when enabled hides the search bar from Today View.
**Describe alternatives you've considered**
None, it's pretty straight forward.
**Additional context**

**Comment by MTACS** [comment]
Added in 1.8.1
