### ISSUE TITLE
STATUSBAR BUG

### ISSUE THREAD

**Issue by dinouse** [MTACS/Lynx#415]
**Describe the bug**
Statusbar hide anywhere not working

**To Reproduce**
latest update and the feature doesn't work again

**Expected behavior**
The statusbar shouldnt appear again. But it still apearred
**Screenshots**
No screenshot.

**iDevice Information (please complete the following information):**
 - Device: [iPhone X]
 - OS: [iOS 13.2.2]
 - Package Manager used to install Lynx: [Zebra, Cydia, Installer]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.7.3]
 - Jailbreak Used: [Checkra1n]

**Additional context**
nope. Just statusbar not working

**Comment by MTACS** [comment]
Fixed in 1.8

**Comment by dinouse** [comment]
no update appeared lol
