### ISSUE TITLE
Hide statusbar

### ISSUE THREAD

**Issue by Jazz696** [MTACS/Lynx#419]
**Describe the bug**
Please fixed hide statusbar sometimes still stuck on homescreen after opening app

**Screenshots**
![2F376E20-3770-4987-B9F1-3018AAEC46BA](https://user-images.githubusercontent.com/70351339/92572102-2b207480-f2ae-11ea-8593-0eefc3061b5f.png)

![19376E66-51CA-4969-B1EB-5081E5B2824E](https://user-images.githubusercontent.com/70351339/92572213-52774180-f2ae-11ea-8851-aeb4bfe1d514.png)

**iDevice Information (please complete the following information):**
 - Device: [iPSE]
 - OS: [iOS 13.3.1]
 - Package Manager used to install Lynx: [Cydia]
 - Lynx Version [1.7.3] 
 - Jailbreak Used: [unc0ver]

**Comment by MTACS** [comment]
Fixed in the latest beta of 1.8
