### ISSUE TITLE
Hide bar on Homescreen

### ISSUE THREAD

**Issue by jdcyoc** [MTACS/Lynx#42]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MTACS** [comment]
Do you mean the home bar?

**Comment by jdcyoc** [comment]
The ability to have the Homebar only show on the lock screen but not within apps.

**Comment by jdcyoc** [comment]
Similar to the auto hide homebar tweak, perhaps implementing it to your tweak

**Comment by jdcyoc** [comment]
Also, just a thought, any chance you add the CC First Teach Symbol to show on the Lockscreen all the time, I think CydiaGeek has it on SmoothlockX, but it’s very buggy. 

Thank you and I enjoy your tweak; it was worth the purchase

**Comment by MTACS** [comment]
You can already disable it globally, I had an option to disable separately
on the lock screen and in apps but it broke control center so I disabled
that option

**Comment by jdcyoc** [comment]
> You can already disable it globally, I had an option to disable separately on the lock screen and in apps but it broke control center so I disabled that option
> […](#)

Ohhh I see. Yeah that’s the sort of customization I was looking for it. For now AutoHideHomeBarX would do.

Thank you and any chance on the other request about the CC grabber symbol always appearing

**Comment by jdcyoc** [comment]
![8B4AB4F3-BD36-46E0-BE3D-D1368A89DA5D](https://user-images.githubusercontent.com/60438443/73372495-50afbf00-4285-11ea-9580-ad6245c91e1e.jpeg)
