### ISSUE TITLE
Hide Icons feature broke on Lynx 1.8

### ISSUE THREAD

**Issue by kegobass** [MTACS/Lynx#422]
**Describe the bug**
I hide most of my icons on the HS.  This was working fine on 1.73.  After upgrading to 1.8, I can no longer hide new icons.  The toggle works but the icons remain on the HS.

**To Reproduce**

- Add a new app (from the Appstore)
- Attempt to hide icon on HS within Lynx
- Respring
- App icon is still on the HS

**Expected behavior**

- Expect the icon to be hidden

**iDevice Information (please complete the following information):**
 - Device: iPhone X
 - OS: [iOS 13.7
 - Package Manager used to install Lynx:  Zebra
 - Lynx Version (Can be found at the bottom of Settings pane): 1.8
 - Jailbreak Used: Odysseyra1n

**Additional context**
Works fine on 1.73 which I downgraded to in the meantime

**Comment by MTACS** [comment]
Fixed in 1.8.1
