### ISSUE TITLE
hide statusbar on lockscreen

### ISSUE THREAD

**Issue by real-mizuya** [MTACS/Lynx#427]
Hello, can you add an option to completely hide the statusbar on lockscreen? Thank you very much 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MTACS** [comment]
Lynx > Status Bar > Hide on Lockscreen

**Comment by real-mizuya** [comment]
Oh man, I really feel stupid right now, didn't see it 🙈

**Comment by MTACS** [comment]
No worries 😀
