### ISSUE TITLE
Hiding separator lines isn’t working

### ISSUE THREAD

**Issue by AwesomeCookieL** [MTACS/Lynx#428]
**Describe the bug**
A clear and concise description of what the bug is. Basically I enable hide separating lines and I respring and it seems to work fine until in the settings app I scroll and then it comes right back up for some reason 

**To Reproduce**
Steps to reproduce the behavior: simply scrolling in the scrolling up and down and the cause of this bug was Noctis Neo and how did I figure this out you may ask? Well what I did was I used choicy and disabled Noctis neo for settings and then I re enable it and then it showed the bug.

**Expected behavior**
A clear and concise description of what you expected to happen. What I expect from you is to fix the fact that it isn’t hiding properly.

**Screenshots**
![2A1EEDD9-1A81-4B93-83DB-D310FF18903E](https://user-images.githubusercontent.com/70043231/94215486-197ed400-ff20-11ea-8665-ae6207a07d53.png)

**iDevice Information (please complete the following information):**
 - Device: [iPhone 8 and iPad 6th generation]
 - OS: [iOS 13.4.1 and 13.5.1]
 - Package Manager used to install Lynx: [Zebra, Cydia, Installer]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.8.1]
 - Jailbreak Used: [Odysseyra1n]

**Additional context**
Add any other context about the problem here.no but if you fix this then thank you

**Comment by MTACS** [comment]
Changed the methods used in 1.9, hides it everywhere including places it didn't before (Swift apps, custom views...) should be working fully in 1.9
