### ISSUE TITLE
App Switcher issues

### ISSUE THREAD

**Issue by Elcvise** [MTACS/Lynx#429]
**Describe the bug**
I didn’t enable the 3D Touch to kill feature, and when I long press or press hard at the app switcher card, it still has a haptic feedback, and after that, sometimes it crashed or stuck.
**To Reproduce**
Disable 3D Touch to kill and tap at the app switcher card.
**Expected behavior**
Just no need haptic feedback, be normal, after all, I didn’t enable the 3D Touch to kill feature. 
**Screenshots**

**iDevice Information (please complete the following information):**
 - Device: [iPhone Xs]
 - OS: [iOS 13.5]
 - Package Manager used to install Lynx: [Zebra]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.8.1]
 - Jailbreak Used: [unc0ver]

**Additional context**

**Comment by MTACS** [comment]
Fixed in 1.9-beta
