### ISSUE TITLE
Date as carrier

### ISSUE THREAD

**Issue by TurtleTurtles** [MTACS/Lynx#433]
**Describe the the bug**
When using the date as the carrier, sometimes on a new day, the date doesn’t change until after respring. 

**To Reproduce**
Using date as carrier. 

**Expected behavior**
Date changing. 

**Screenshots**
![EDC60092-20D0-465A-B1B0-B8B32671DC06](https://user-images.githubusercontent.com/33901377/94996157-e5835e80-0570-11eb-9609-a3fc25954e29.jpeg)

**iDevice Information (please complete the following information):**
 - Device: [iPhone 7+]
 - OS: [iOS 13.6.1]
 - Package Manager used to install Lynx: [Cydia]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.8.1]
 - Jailbreak Used: [Checkra1n]

**Comment by MTACS** [comment]
Fixed in 1.9
