### ISSUE TITLE
remove the top blur in Apple maps 

### ISSUE THREAD

**Issue by Elcvise** [MTACS/Lynx#434]
When using Apple stock maps, it has a blur shadow on the top screen for notched iPhone, is there any chance you could remove it, just like the Google maps does.
![A7E89970-6780-4EE7-9A72-ABE5F2AEE988](https://user-images.githubusercontent.com/36326547/95271480-90956000-0870-11eb-8c68-42d91d82831d.jpeg)

**Comment by MTACS** [comment]
Added in 1.9-beta4
