### ISSUE TITLE
Beta1.9 causes menu (?) to freeze 

### ISSUE THREAD

**Issue by whiteblacksmiths** [MTACS/Lynx#436]
**Describe the bug**
not sure where else this bug applies to, but i realised it occurred in package managers like Zebra and Installer (Cydia worked fine). basically, when touching any menu — pressing into tweaks to view their description, or even on Zebra‘s homepage (Transfer sources, Wishlist), the app freezes and ultimately force exits. invoking app switcher still works, but touches from within each app is not registered. even after force exiting, there is no crashlog in cr4shed. downgrading to v1.8.1 corrects the behaviour. 

**To Reproduce**
Steps to reproduce the behavior: just tap on a random cell in Zebra or Installer (changelog in Zebra works fine though)

**Expected behavior**
the menus to show correctly 

**Screenshots**
-

**iDevice Information (please complete the following information):**
 - Device: [iPhone X] iPX
 - OS: [iOS 13.2.2] 13.5
 - Package Manager used to install Lynx: [Zebra, Cydia, Installer] Zebra
 - Lynx Version (Can be found at the bottom of Settings pane): [1.0.3] bug occurred in v1.9
 - Jailbreak Used: [Checkra1n, unc0ver] u0

**Additional context**
-

**Comment by MTACS** [comment]
Fixed in latest betas
