### ISSUE TITLE
Dark PopUp and Alerts 

### ISSUE THREAD

**Issue by JohnesBilly2569** [MTACS/Lynx#444]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JohnesBilly2569** [comment]
Need features in next update to dark Alert and popUp

**Comment by JohnesBilly2569** [comment]
![image](https://user-images.githubusercontent.com/49144063/98448935-bc8e5480-2140-11eb-9a9c-d15e64f31e95.png)


Can this feature be added in the next update of lynx tweak , which is to make alerts, action sheet, and 3D  background color dark .please i don't like white popup .

**Comment by MTACS** [comment]
Added in 1.9.2
