### ISSUE TITLE
Clock on lockscreen

### ISSUE THREAD

**Issue by tahseenalaaj** [MTACS/Lynx#446]
Lynx 1.9.2 iPhone XS MAX Unc0ver 13.5
When I change value of clock ( time ) in lockscreen to 0.6 or any value after while or when I charge my device the time back to normal white color when the value was 1
![ACEFD7D3-FC74-4786-8732-AD73D80F9E3B](https://user-images.githubusercontent.com/66691899/100490260-3a83c100-312b-11eb-9ca1-7cece5b37347.png)

**Comment by MTACS** [comment]
It's probably not refreshing it, I'll get it fixed in the next update

**Comment by tahseenalaaj** [comment]
Thanks, hope that

**Comment by MTACS** [comment]
Fixed in 1.9.3
