### ISSUE TITLE
Some Bugs

### ISSUE THREAD

**Issue by Yolokung** [MTACS/Lynx#45]
**Describe the bug**
1. “Hide App Labels” option in App Switcher sometimes work, mostly don’t.
2. “Hide Clock” option in Status Bar hide the carrier name instead.

**To Reproduce**
1. Enable “Hide App Labels” option in App Switcher.
2. Enable “Hide Clock” option in Status Bar.

**Expected behavior**
1. “Hide App Labels” option should always work.
2. “Hide Clock” option should hide Time or Alarm icon in status bar. (idk what you mean by “Hide Clock” in Status Bar)

**Screenshots**
1. App Switcher
![App Switcher](https://user-images.githubusercontent.com/48957811/73517819-33b6ef80-442f-11ea-8336-35acb9cd001a.jpeg)

2. Status Bar
![Status Bar](https://user-images.githubusercontent.com/48957811/73517832-403b4800-442f-11ea-9a2b-3f1664f6eacf.jpeg)

**iDevice Information**
 - Device: iPhone 7
 - OS: iOS 13.3.1
 - Package Manager used to install Lynx: Zebra
 - Lynx Version: 1.1.1

**Comment by MTACS** [comment]
Are the App Switcher bugs only present when using the gridswitcher or always?

**Comment by Yolokung** [comment]
Only using the gridswitcher and I noticed that there’s a daemon called “druid” that is killing my battery and preventing me from moving icons around.

**Comment by MTACS** [comment]
Use Choicy to disable tweak injection in druid

**Comment by MTACS** [comment]
Added addition check for grid switcher layout and disabled injection into druid as of 1.1.2
