### ISSUE TITLE
Photos metadata not working on v1.9.4 and photos size is inaccurate.

### ISSUE THREAD

**Issue by AymenKcm1** [MTACS/Lynx#456]
**Describe the bug**
1.Photos metadata is not working.
2.The photo size is not accurate. 

**To Reproduce**
Update to v1.9.4, enable the option, respring, open Photos app.

**Expected behavior**
1.The photo metadata is shown on top.
2.The size should be in kb instead of showing 0.00 mb. 

**Screenshots**
![image](https://user-images.githubusercontent.com/67245917/102443025-0dd61180-4026-11eb-8cf3-f7b365c5feb1.jpeg)

![image](https://user-images.githubusercontent.com/67245917/102443052-1dedf100-4026-11eb-9ee6-146caceafc48.jpeg)

**iDevice Information (please complete the following information):**
 - Device: iPhone Xs Max (iPhone11,6)
 - OS: iOS 13.5
 - Package Manager used to install Lynx: Zebra
 - Lynx Version : 1.9.4
 - Jailbreak Used: unc0ver

**Additional context**
-￼

**Comment by MTACS** [comment]
Fixed in 1.9.4-1, I removed the image file size, converting it to kilobytes still returned 0
