### ISSUE TITLE
Hide icons not working in 1.1.2.1 (and persistent update)

### ISSUE THREAD

**Issue by zibo29** [MTACS/Lynx#46]
- “Hide Icons Label” no more working
- persistent cydia update to 1.1.2.1 although installed (Lynx version keeps saying 1.1.2)
**iDevice Information (please complete the following information):**
 - Device: [iPhone 7 Plus]
 - OS: [iOS 13.3.1]
 - Package Manager used to install Lynx: Cydia
 - Lynx Version [1.1.2]

**Additional context**

**Comment by MTACS** [comment]
Fixed in 1.1.3
