### ISSUE TITLE
Icon outer shadow function lets lags in app library in default view

### ISSUE THREAD

**Issue by Decodeme7** [MTACS/Lynx#463]
**Describe the bug**
Icon outer shadow function lets lags in app library in default view when i put list view it becames to normal and not buggy

**To Reproduce**
 when i put list view it becames to normal and not buggy

**iDevice Information (please complete the following information):**
 - Device: [iPhone 11]
 - OS: [iOS 14.3]
 - Package Manager used to install Lynx: [Cydia, Installer]
 - Lynx Version (Can be found at the bottom of Settings pane): [2.0]
 - Jailbreak Used: [unc0ver]

**Comment by MTACS** [comment]
Closed as it's a Lynx 2 bug, currently being worked on, but might not be fully lag free due to the way iOS draws shadows
