### ISSUE TITLE
Springboard clock 

### ISSUE THREAD

**Issue by squall231** [MTACS/Lynx#47]
**Describe the bug**
I havn’t the possibility to hide clock on springboard.

**To Reproduce**
In the status bar menu.

**Screenshots**
![1B6E2CB6-E924-4F6E-BED4-B4B574EB8EF5](https://user-images.githubusercontent.com/60690679/73827414-cc6ab800-47ff-11ea-86b6-9f6c0bcdc747.png)

**iDevice Information (please complete the following information):**
 - Device: IPhone 8 Plus 
 - OS: iOS 13.3
 - Package Manager used to install Lynx : Cydia
 - Lynx Version : 1.1.2

**Comment by MTACS** [comment]
I'll add it

**Comment by squall231** [comment]
Amazing !
Thx for your work 👍
