### ISSUE TITLE
Can’t move app icons 

### ISSUE THREAD

**Issue by bryanlaramore** [MTACS/Lynx#51]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**iDevice Information (please complete the following information):**
 - Device: [iPhone X]
 - OS: [iOS 13.2.2]
 - Package Manager used to install Lynx [Zebra, Cydia, Installer]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.0.3]

**Additional context**

**Comment by MTACS** [comment]
This is due to a tweak injecting into Apple's DragUI daemon. As of Lynx 1.1.3 I've disabled injection into it. If the issue still persists, use Choicy to disable injection into that daemon, which is probably a good idea whether Lynx is installed or not. 

```objective-c
NSString *activeProcessName = [[NSClassFromString(@"NSProcessInfo") processInfo] arguments].firstObject.lastPathComponent;

NSArray *blackList = [NSArray arrayWithObjects:@"druid", @"com.apple.DragUI.druid", nil];

if (enabled) {
     if (![blackList containsObject:activeProcessName]) {
          %init(Tweak) // Initializes tweak
     }
}
```
