### ISSUE TITLE
Icon rearrange 

### ISSUE THREAD

**Issue by afnas214** [MTACS/Lynx#54]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**iDevice Information (please complete the following information):**
 - Device: [iPhone X]
 - OS: [iOS 13.2.2]
 - Package Manager used to install Lynx [Zebra, Cydia, Installer]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.0.3]

**Additional context**

**Comment by afnas214** [comment]
I can’t rearrange the icon

**Comment by MTACS** [comment]
Disable tweak injection into the daemon called druid, it’s a problem with Cephei as it’s explicitly disabled within Lynx

**Comment by emlapzo9x** [comment]
> Disable tweak injection into the daemon called druid, it’s a problem with Cephei as it’s explicitly disabled within Lynx

when i try to disable tweak injection and do a respring, it will take me to a respring loop so i need to enable tweak injection again, please fix this.

**Comment by MTACS** [comment]
Probably not an issue with Lynx then, did you try Choicy to disable it?

**Comment by emlapzo9x** [comment]
> Probably not an issue with Lynx then, did you try Choicy to disable it?

yes i did, and i'm sure that the problem was from Lynx and Choicy. I tried to disable cydia addons on both tweak and my phone doesn't have  respring loop anymore.

**Comment by MTACS** [comment]
Lynx is disabled by default after and explicitly cannot load into the process if it matches any Apple daemon
