### ISSUE TITLE
Set ‘Notification Center’ text applies to group message headers

### ISSUE THREAD

**Issue by herrkugla** [MTACS/Lynx#56]
**Describe the bug**
Setting Notification Center text applies to grouped messages. Even if no custom text is applied it still shows as ‘Notification Center’. 

**To Reproduce**
Install fresh Lynx, look at grouped notification headers, apply custom text and it will apply to grouped notifications and overall header.

**Expected behavior**
Only the overall header should changed, not header for grouped messages. 

**Screenshots**
![1B0016C4-D6A4-4AB3-89FB-4376E850E1C8](https://user-images.githubusercontent.com/8568594/74590934-d7c89b00-4fd8-11ea-81c5-245aad273700.jpeg)

**iDevice Information (please complete the following information):**
 - Device: [iPhone X]
 - OS: [iOS 13.3]
 - Package Manager: [Cydia]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.1.4]

**Comment by MTACS** [comment]
Fixed in upcoming version 1.1.5
