### ISSUE TITLE
Lynx Preferences Crashing

### ISSUE THREAD

**Issue by ColeSchaefer** [MTACS/Lynx#57]
**Describe the bug**
The preference panel force closes when selecting either Messages or Systemwide. 

**To Reproduce**
1.) Open Settings
2.) Tap Lynx
3.) Tap Messages (or Systemwide and scroll any amount)
4.) Settings app will crash and close. 

**Expected behavior**
Instead of crashing, I expected that it would open the preference panes for each of those categories.  

**iDevice Information:**
 - Device: [iPhone 7]
 - OS: [iOS 13.2.2]
 - Package Manager used to install Lynx [Zebra]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.1.4]

**Comment by MTACS** [comment]
Make sure you have the proper dependencies installed, this is most likely caused by using an unofficial version of libcolorpicker
