### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by Exp0rt** [MTACS/Lynx#59]
Bro may you add option in Lynx to disable 3DTouch widgets.

**Comment by MTACS** [comment]
Do you mean this? 
![PNG image](https://user-images.githubusercontent.com/13209789/74612110-58b68e00-50d0-11ea-94de-7700ed7f0a25.png)

**Comment by Arablag** [comment]
Yeah all of them (Phone, Weather, Photo, etc). Thank you
My twitter account stopped sorry bro (@Arablag) I will contact you from new 1 soon.

**Comment by MTACS** [comment]
Ok I'll see what I can do

**Comment by Arablag** [comment]
Good luck
