### ISSUE TITLE
Lynx Conflict with “NoCShare” tweak

### ISSUE THREAD

**Issue by ez0x** [MTACS/Lynx#65]
**Describe the bug**
NoCShare tweak doesn’t work if Lynx is installed 

 - Device: [iPhone Pro max]
 - OS: [iOS 13.3]
 - Package Manager used to install Lynx [Cydia]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.1.5-4]

**Comment by MTACS** [comment]
Are you sure that it's not another tweak causing the issue? I just installed NoCShare myself and it worked fine. I also don't have any hooks related to the share sheet, but I'll look over my code again just to make sure its not done by accident
