### ISSUE TITLE
1.1.5-4 issues with JellyFish

### ISSUE THREAD

**Issue by zibo29** [MTACS/Lynx#68]
**Describe the bug**
Jellyfish keeps the slimmer logo, ignoring other settings (i'm not having this issue on 1.1.5-1 to whom I've downgraded 

**To Reproduce**
Install Jellyfish with Thicc appeareance with 1.1.5-4

**iDevice Information (please complete the following information):**
 - Device: [iPhone 7 Plus with Little11]
 - OS: [iOS 13.3.1]
 - Package Manager used to install Lynx [Cydia]
 - Lynx Version [1.1.5-4]

**Comment by MTACS** [comment]
Already fixed

**Comment by zibo29** [comment]
Ok thanks for fast support, will be fixed in upcoming version 1.1.5-5?
