### ISSUE TITLE
Same Size Status bar

### ISSUE THREAD

**Issue by xLinoelx** [MTACS/Lynx#7]
Is it possible to create an option so that the status bar is the same size on the homescreen and on the lockscreen?  in other versions of iOS it was possible with some tweaks but they no longer work in iOS 13.

Here I leave some guide images
Homescreen
![27D11634-A099-43EF-8019-58085AB6082F](https://user-images.githubusercontent.com/47705964/72673737-00df2580-3a45-11ea-8251-cf2e85ca49f6.jpeg)

Lockscreen 

![48EC2E96-84A9-48D2-BBFD-2F3770750666](https://user-images.githubusercontent.com/47705964/72673757-15bbb900-3a45-11ea-95e6-b29a32eb00a1.jpeg)

**Comment by MTACS** [comment]
I’ll see what I can do

**Comment by xLinoelx** [comment]
> I’ll see what I can do

Thanks!
