### ISSUE TITLE
Hide “Send beta Feedback” in 3DTouch Menu

### ISSUE THREAD

**Issue by p1neapplecfw** [MTACS/Lynx#71]
I would like to be able to hide the “Send beta Feedback” option you see when you 3DTouch on a beta application

Example: https://imgur.com/a/ibAsp04

**Comment by MTACS** [comment]
I’ll see what I can do, I’ll have to find a beta app to test as I need the actual name of the type of shortcut. If you have the tweak Flexing and wouldn’t mind I could add it from there

**Comment by MTACS** [comment]
Fixed in latest update
