### ISSUE TITLE
Sick Not Hidden 

### ISSUE THREAD

**Issue by carlthetomato** [MTACS/Lynx#75]
**Describe the bug**
The dock still has the grey background even though it is set to hidden. I have no other conflicting tweaks that would cause it to not work properly and I’ve respiringed and reset many times with no change 
**To Reproduce**

**Expected behavior**

**Screenshots**

**iDevice Information (please complete the following information):**
 - Device: [iPhone X]
 - OS: [iOS 13.2.2]
 - Package Manager used to install Lynx [Zebra, Cydia, Installer]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.0.3]

**Additional context**

**Comment by MTACS** [comment]
Update to the latest version of Lynx, as it says you’re using version 1.0.3
