### ISSUE TITLE
Hide battery percentage in CC

### ISSUE THREAD

**Issue by mnsaleem** [MTACS/Lynx#88]
An option under Status bar settings to hide the percentage indicator that is shown when opening Control center

**Comment by MTACS** [comment]
Are you talking about iPhone X style phones?

**Comment by mnsaleem** [comment]
Yes, exactly. I am currenty using BatteryPercentageX for this, as well as having the percentage number inside the battery. Would it be possible to add something similar in Lynx?

**Comment by MTACS** [comment]
Added in 1.1.8
