### ISSUE TITLE
Report Bug Lynx 1.1.7-3

### ISSUE THREAD

**Issue by audris42** [MTACS/Lynx#91]
**Describe the bug**
not activate the 5 columns option

**iDevice Information:**
 - Device: [iPhone 7]
 - OS: [iOS 13.3]
 - Package Manager used to install Lynx [Installer]
 - Lynx Version (Can be found at the bottom of Settings pane): [1.1.7-3]

**Additional context**

does not display the 5 columns requested on the SpringBoard

**Comment by MTACS** [comment]
Bad logic in checking whether the current row of icons is in the dock or not, hopefully the next update will fix it, just waiting on beta testers
