### ISSUE TITLE
Hide dock background does not work

### ISSUE THREAD

**Issue by ghost** [MTACS/Lynx#92]
**Describe the bug**
Hide Dock background option does not work

**To Reproduce**
Enable the option

**Expected behavior**
To hide the docks background

**Screenshots**
https://imgur.com/a/Wpo9Edm

**iDevice Information (please complete the following information):**
 - Device: **iPhone X**
 - OS: **iOS 13.3**
 - Package Manager used to install Lynx [Zebra, Cydia, Installer]: **Zebra**
 - Lynx Version (Can be found at the bottom of Settings pane): **1.1.7**

**Comment by noahmaranesi** [comment]
Still has not been fixed with Lynx 1.1.8. iPhone XS Max, iOS 13.3.0.

**Comment by MTACS** [comment]
Is this when using the stock iOS dock or are you using another Dock tweak like Snowboard’s Dock extension or FloatyDock? I used two different methods to hide the background just to be safe

**Comment by noahmaranesi** [comment]
@MTACS: SnowBoard was affecting it. I was however running no Dock Extensions. Lynx should still be able to hide the Dock background, as SnowBoard does not affect it without a Dock Extension (i.e. there’s no “Hide Dock Background” in SnowBoard; just whatever theme is applied)

**Comment by MTACS** [comment]
I’ll reach out to SparkDev to see what I can do, sometimes when two tweaks override the same thing, which ever is loaded first by substrate/substitute overrides the other. I will do some testing as I’ve had this bug before but it may require more digging. Until then make sure that the option is enabled in SnowBoard until I can find a way to force override it
