### ISSUE TITLE
Battery percentage in the battery 

### ISSUE THREAD

**Issue by KuroTheBang** [MTACS/Lynx#94]
**Is your feature request related to a problem? Please describe.**
It sucks that Apple won’t show percentage on notch devices, although having the percentage battery implemented in iOS (even for notch devices)

**Describe the solution you'd like**
There is a tweak called Arkrome, which sadly is EoL, which enables the internal %-sign into the battery logo.

**Describe alternatives you've considered**
Had to install Arkrome. But less tweaks = less processes = more battery. 

**Additional context**
https://repo.packix.com/package/com.dpkg.arkromepro/

**Comment by MTACS** [comment]
Added in 1.1.8-1
