### ISSUE TITLE
Crash occurs when 3D Touching on folder with Average Color enabled under Badges section

### ISSUE THREAD

**Issue by noahmaranesi** [MTACS/Lynx#99]
1. Enable **Average Color** (Lynx → System Wide → Badges)
2. 3D Touch on folder with badge
3. Crash occurs

---

- Device: iPhone XS Max
- Operating system: iOS 13.3.0
- Lynx version: 1.0.3

**Comment by MTACS** [comment]
Definitely a bug, doesn't create a crash log for me, looking into it
